# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Models::Entity`.
# Please instead update this file by running `bin/tapioca dsl Models::Entity`.


class Models::Entity
  extend T::Generic
  include GeneratedAttributeMethods
  include GeneratedAssociationMethods
  extend GeneratedClassMethods

  Elem = type_template { { fixed: ::Models::Entity } }

  module GeneratedAssociationMethods
    sig do
      params(
        opts: T::Hash[Symbol, T.untyped],
        block: T.nilable(T.proc.params(dataset: ::Models::Account::PrivateDataset).returns(::Sequel::Dataset))
      ).returns(T::Array[::Models::Account])
    end
    def accounts(opts = T.unsafe(nil), &block); end

    sig { returns(::Models::Account::PrivateDataset) }
    def accounts_dataset; end

    sig do
      params(
        opts: T::Hash[Symbol, T.untyped],
        block: T.nilable(T.proc.params(dataset: ::Models::AchTransaction::PrivateDataset).returns(::Sequel::Dataset))
      ).returns(T::Array[::Models::AchTransaction])
    end
    def ach_transactions(opts = T.unsafe(nil), &block); end

    sig { returns(::Models::AchTransaction::PrivateDataset) }
    def ach_transactions_dataset; end

    sig do
      params(
        object: T.any(::Models::Account, T::Hash[Symbol, T.untyped], Integer)
      ).returns(T.nilable(::Models::Account))
    end
    def add_account(object); end

    sig do
      params(
        object: T.any(::Models::AchTransaction, T::Hash[Symbol, T.untyped], String)
      ).returns(T.nilable(::Models::AchTransaction))
    end
    def add_ach_transaction(object); end

    sig do
      params(
        object: T.any(::Models::Security, T::Hash[Symbol, T.untyped], String)
      ).returns(T.nilable(::Models::Security))
    end
    def add_borrowed_security(object); end

    sig do
      params(
        object: T.any(::Models::Security, T::Hash[Symbol, T.untyped], String)
      ).returns(T.nilable(::Models::Security))
    end
    def add_issued_security(object); end

    sig do
      params(
        object: T.any(::Models::Subscription, T::Hash[Symbol, T.untyped], String)
      ).returns(T.nilable(::Models::Subscription))
    end
    def add_subscription(object); end

    sig do
      params(
        opts: T::Hash[Symbol, T.untyped],
        block: T.nilable(T.proc.params(dataset: ::Models::Security::PrivateDataset).returns(::Sequel::Dataset))
      ).returns(T::Array[::Models::Security])
    end
    def borrowed_securities(opts = T.unsafe(nil), &block); end

    sig { returns(::Models::Security::PrivateDataset) }
    def borrowed_securities_dataset; end

    sig do
      params(
        opts: T::Hash[Symbol, T.untyped],
        block: T.nilable(T.proc.params(dataset: ::Models::Security::PrivateDataset).returns(::Sequel::Dataset))
      ).returns(T::Array[::Models::Security])
    end
    def issued_securities(opts = T.unsafe(nil), &block); end

    sig { returns(::Models::Security::PrivateDataset) }
    def issued_securities_dataset; end

    sig { params(object: T.any(::Models::Account, Integer)).returns(T.nilable(::Models::Account)) }
    def remove_account(object); end

    sig { params(object: T.any(::Models::AchTransaction, String)).returns(T.nilable(::Models::AchTransaction)) }
    def remove_ach_transaction(object); end

    sig { returns(T.nilable(T::Array[::Models::Account])) }
    def remove_all_accounts; end

    sig { returns(T.nilable(T::Array[::Models::AchTransaction])) }
    def remove_all_ach_transactions; end

    sig { returns(T.nilable(T::Array[::Models::Security])) }
    def remove_all_borrowed_securities; end

    sig { returns(T.nilable(T::Array[::Models::Security])) }
    def remove_all_issued_securities; end

    sig { returns(T.nilable(T::Array[::Models::Subscription])) }
    def remove_all_subscriptions; end

    sig { params(object: T.any(::Models::Security, String)).returns(T.nilable(::Models::Security)) }
    def remove_borrowed_security(object); end

    sig { params(object: T.any(::Models::Security, String)).returns(T.nilable(::Models::Security)) }
    def remove_issued_security(object); end

    sig { params(object: T.any(::Models::Subscription, String)).returns(T.nilable(::Models::Subscription)) }
    def remove_subscription(object); end

    sig do
      params(
        opts: T::Hash[Symbol, T.untyped],
        block: T.nilable(T.proc.params(dataset: ::Models::Subscription::PrivateDataset).returns(::Sequel::Dataset))
      ).returns(T::Array[::Models::Subscription])
    end
    def subscriptions(opts = T.unsafe(nil), &block); end

    sig { returns(::Models::Subscription::PrivateDataset) }
    def subscriptions_dataset; end
  end

  module GeneratedAttributeMethods
    sig { returns(Time) }
    def created_at; end

    sig { params(value: T.nilable(Time)).returns(T.nilable(Time)) }
    def created_at=(value); end

    sig { returns(String) }
    def holder_uuid; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def holder_uuid=(value); end

    sig { returns(Integer) }
    def id; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def id=(value); end

    sig { returns(String) }
    def name; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def name=(value); end

    sig { returns(String) }
    def role; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def role=(value); end

    sig { returns(Time) }
    def updated_at; end

    sig { params(value: T.nilable(Time)).returns(T.nilable(Time)) }
    def updated_at=(value); end
  end

  module GeneratedClassMethods
    sig { params(args: T.untyped).returns(T.nilable(::Models::Entity)) }
    def [](*args); end

    sig { params(block: T.untyped).returns(T::Array[::Models::Entity]) }
    def all(&block); end

    sig { params(args: T.untyped, block: T.untyped).returns(Integer) }
    def count(*args, &block); end

    sig do
      params(
        values: T::Hash[Symbol, T.untyped],
        block: T.nilable(T.proc.params(arg0: ::Models::Entity).void)
      ).returns(::Models::Entity)
    end
    def create(values = T.unsafe(nil), &block); end

    sig { returns(::Models::Entity::PrivateDataset) }
    def dataset; end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def distinct(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def eager(*args, &block); end

    sig { returns(T::Boolean) }
    def empty?; end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def exclude(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def filter(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(T.nilable(::Models::Entity)) }
    def first(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity) }
    def first!(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def for_update(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def group(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def group_by(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def having(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(T.nilable(::Models::Entity)) }
    def last(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def limit(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def offset(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def order(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def order_by(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def reverse(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def select(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def select_append(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def where(*args, &block); end

    sig { params(pk: T.untyped).returns(T.nilable(::Models::Entity)) }
    def with_pk(pk); end

    sig { params(pk: T.untyped).returns(::Models::Entity) }
    def with_pk!(pk); end
  end

  module GeneratedDatasetMethods
    sig { params(block: T.untyped).returns(T::Array[::Models::Entity]) }
    def all(&block); end

    sig { params(args: T.untyped, block: T.untyped).returns(Integer) }
    def count(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def distinct(*args, &block); end

    sig { params(block: T.proc.params(arg0: ::Models::Entity).void).returns(::Models::Entity::PrivateDataset) }
    def each(&block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def eager(*args, &block); end

    sig { returns(T::Boolean) }
    def empty?; end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def exclude(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def filter(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(T.nilable(::Models::Entity)) }
    def first(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity) }
    def first!(*args, &block); end

    sig do
      type_parameters(:U)
        .params(
          block: T.proc.params(arg0: ::Models::Entity).returns(T.type_parameter(:U))
        ).returns(T::Array[T.type_parameter(:U)])
    end
    def flat_map(&block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def for_update(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def group(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def group_by(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def having(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(T.nilable(::Models::Entity)) }
    def last(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def limit(*args, &block); end

    sig do
      type_parameters(:U)
        .params(
          block: T.proc.params(arg0: ::Models::Entity).returns(T.type_parameter(:U))
        ).returns(T::Array[T.type_parameter(:U)])
    end
    def map(&block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def offset(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def order(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def order_by(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def reverse(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def select(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def select_append(*args, &block); end

    sig { returns(T.nilable(::Models::Entity)) }
    def single_record; end

    sig { returns(T::Array[::Models::Entity]) }
    def to_a; end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Entity::PrivateDataset) }
    def where(*args, &block); end

    sig { params(pk: T.untyped).returns(T.nilable(::Models::Entity)) }
    def with_pk(pk); end

    sig { params(pk: T.untyped).returns(::Models::Entity) }
    def with_pk!(pk); end
  end

  class PrivateDataset < ::Sequel::Dataset
    extend T::Generic
    include GeneratedDatasetMethods

    Elem = type_member { { fixed: ::Models::Entity } }
  end
end
