# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Models::Security`.
# Please instead update this file by running `bin/tapioca dsl Models::Security`.


class Models::Security
  extend T::Generic
  include GeneratedAttributeMethods
  include GeneratedAssociationMethods
  extend GeneratedClassMethods

  Elem = type_template { { fixed: ::Models::Security } }

  module GeneratedAssociationMethods
    sig do
      params(
        opts: T::Hash[Symbol, T.untyped],
        block: T.nilable(T.proc.params(dataset: ::Models::Account::PrivateDataset).returns(::Sequel::Dataset))
      ).returns(T::Array[::Models::Account])
    end
    def accounts(opts = T.unsafe(nil), &block); end

    sig { returns(::Models::Account::PrivateDataset) }
    def accounts_dataset; end

    sig do
      params(
        object: T.any(::Models::Account, T::Hash[Symbol, T.untyped], Integer)
      ).returns(T.nilable(::Models::Account))
    end
    def add_account(object); end

    sig do
      params(
        object: T.any(::Models::Repayment, T::Hash[Symbol, T.untyped], String)
      ).returns(T.nilable(::Models::Repayment))
    end
    def add_repayment(object); end

    sig do
      params(
        object: T.any(::Models::Subscription, T::Hash[Symbol, T.untyped], String)
      ).returns(T.nilable(::Models::Subscription))
    end
    def add_subscription(object); end

    sig do
      params(
        opts: T::Hash[Symbol, T.untyped],
        block: T.nilable(T.proc.params(dataset: ::Models::Entity::PrivateDataset).returns(::Sequel::Dataset))
      ).returns(T.nilable(::Models::Entity))
    end
    def borrower(opts = T.unsafe(nil), &block); end

    sig { params(value: T.nilable(::Models::Entity)).returns(T.nilable(::Models::Entity)) }
    def borrower=(value); end

    sig { returns(::Models::Entity::PrivateDataset) }
    def borrower_dataset; end

    sig do
      params(
        opts: T::Hash[Symbol, T.untyped],
        block: T.nilable(T.proc.params(dataset: ::Models::Entity::PrivateDataset).returns(::Sequel::Dataset))
      ).returns(T.nilable(::Models::Entity))
    end
    def issuer(opts = T.unsafe(nil), &block); end

    sig { params(value: T.nilable(::Models::Entity)).returns(T.nilable(::Models::Entity)) }
    def issuer=(value); end

    sig { returns(::Models::Entity::PrivateDataset) }
    def issuer_dataset; end

    sig { params(object: T.any(::Models::Account, Integer)).returns(T.nilable(::Models::Account)) }
    def remove_account(object); end

    sig { returns(T.nilable(T::Array[::Models::Account])) }
    def remove_all_accounts; end

    sig { returns(T.nilable(T::Array[::Models::Repayment])) }
    def remove_all_repayments; end

    sig { returns(T.nilable(T::Array[::Models::Subscription])) }
    def remove_all_subscriptions; end

    sig { params(object: T.any(::Models::Repayment, String)).returns(T.nilable(::Models::Repayment)) }
    def remove_repayment(object); end

    sig { params(object: T.any(::Models::Subscription, String)).returns(T.nilable(::Models::Subscription)) }
    def remove_subscription(object); end

    sig do
      params(
        opts: T::Hash[Symbol, T.untyped],
        block: T.nilable(T.proc.params(dataset: ::Models::Repayment::PrivateDataset).returns(::Sequel::Dataset))
      ).returns(T::Array[::Models::Repayment])
    end
    def repayments(opts = T.unsafe(nil), &block); end

    sig { returns(::Models::Repayment::PrivateDataset) }
    def repayments_dataset; end

    sig do
      params(
        opts: T::Hash[Symbol, T.untyped],
        block: T.nilable(T.proc.params(dataset: ::Models::Subscription::PrivateDataset).returns(::Sequel::Dataset))
      ).returns(T::Array[::Models::Subscription])
    end
    def subscriptions(opts = T.unsafe(nil), &block); end

    sig { returns(::Models::Subscription::PrivateDataset) }
    def subscriptions_dataset; end
  end

  module GeneratedAttributeMethods
    sig { returns(Integer) }
    def annual_rate_bps; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def annual_rate_bps=(value); end

    sig { returns(Integer) }
    def borrower_entity_id; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def borrower_entity_id=(value); end

    sig { returns(Time) }
    def created_at; end

    sig { params(value: T.nilable(Time)).returns(T.nilable(Time)) }
    def created_at=(value); end

    sig { returns(String) }
    def currency; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def currency=(value); end

    sig { returns(T.nilable(String)) }
    def draw_transaction_id; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def draw_transaction_id=(value); end

    sig { returns(T.nilable(String)) }
    def draw_transfer_id; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def draw_transfer_id=(value); end

    sig { returns(String) }
    def id; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def id=(value); end

    sig { returns(Integer) }
    def issuer_entity_id; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def issuer_entity_id=(value); end

    sig { returns(String) }
    def name; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def name=(value); end

    sig { returns(T.nilable(String)) }
    def offering_transaction_id; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def offering_transaction_id=(value); end

    sig { returns(T.nilable(String)) }
    def offering_transfer_id; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def offering_transfer_id=(value); end

    sig { returns(Integer) }
    def principal_minor_units; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def principal_minor_units=(value); end

    sig { returns(Integer) }
    def term_days; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def term_days=(value); end

    sig { returns(Time) }
    def updated_at; end

    sig { params(value: T.nilable(Time)).returns(T.nilable(Time)) }
    def updated_at=(value); end
  end

  module GeneratedClassMethods
    sig { params(args: T.untyped).returns(T.nilable(::Models::Security)) }
    def [](*args); end

    sig { params(block: T.untyped).returns(T::Array[::Models::Security]) }
    def all(&block); end

    sig { params(args: T.untyped, block: T.untyped).returns(Integer) }
    def count(*args, &block); end

    sig do
      params(
        values: T::Hash[Symbol, T.untyped],
        block: T.nilable(T.proc.params(arg0: ::Models::Security).void)
      ).returns(::Models::Security)
    end
    def create(values = T.unsafe(nil), &block); end

    sig { returns(::Models::Security::PrivateDataset) }
    def dataset; end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def distinct(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def eager(*args, &block); end

    sig { returns(T::Boolean) }
    def empty?; end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def exclude(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def filter(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(T.nilable(::Models::Security)) }
    def first(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security) }
    def first!(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def for_update(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def group(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def group_by(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def having(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(T.nilable(::Models::Security)) }
    def last(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def limit(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def offset(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def order(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def order_by(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def reverse(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def select(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def select_append(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def where(*args, &block); end

    sig { params(pk: T.untyped).returns(T.nilable(::Models::Security)) }
    def with_pk(pk); end

    sig { params(pk: T.untyped).returns(::Models::Security) }
    def with_pk!(pk); end
  end

  module GeneratedDatasetMethods
    sig { params(block: T.untyped).returns(T::Array[::Models::Security]) }
    def all(&block); end

    sig { params(args: T.untyped, block: T.untyped).returns(Integer) }
    def count(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def distinct(*args, &block); end

    sig { params(block: T.proc.params(arg0: ::Models::Security).void).returns(::Models::Security::PrivateDataset) }
    def each(&block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def eager(*args, &block); end

    sig { returns(T::Boolean) }
    def empty?; end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def exclude(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def filter(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(T.nilable(::Models::Security)) }
    def first(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security) }
    def first!(*args, &block); end

    sig do
      type_parameters(:U)
        .params(
          block: T.proc.params(arg0: ::Models::Security).returns(T.type_parameter(:U))
        ).returns(T::Array[T.type_parameter(:U)])
    end
    def flat_map(&block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def for_update(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def group(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def group_by(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def having(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(T.nilable(::Models::Security)) }
    def last(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def limit(*args, &block); end

    sig do
      type_parameters(:U)
        .params(
          block: T.proc.params(arg0: ::Models::Security).returns(T.type_parameter(:U))
        ).returns(T::Array[T.type_parameter(:U)])
    end
    def map(&block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def offset(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def order(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def order_by(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def reverse(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def select(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def select_append(*args, &block); end

    sig { returns(T.nilable(::Models::Security)) }
    def single_record; end

    sig { returns(T::Array[::Models::Security]) }
    def to_a; end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::Security::PrivateDataset) }
    def where(*args, &block); end

    sig { params(pk: T.untyped).returns(T.nilable(::Models::Security)) }
    def with_pk(pk); end

    sig { params(pk: T.untyped).returns(::Models::Security) }
    def with_pk!(pk); end
  end

  class PrivateDataset < ::Sequel::Dataset
    extend T::Generic
    include GeneratedDatasetMethods

    Elem = type_member { { fixed: ::Models::Security } }
  end
end
