# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Models::TransferProjection`.
# Please instead update this file by running `bin/tapioca dsl Models::TransferProjection`.


class Models::TransferProjection
  extend T::Generic
  include GeneratedAttributeMethods
  extend GeneratedClassMethods

  Elem = type_template { { fixed: ::Models::TransferProjection } }

  module GeneratedAttributeMethods
    sig { returns(String) }
    def aggregate_id; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def aggregate_id=(value); end

    sig { returns(Time) }
    def created_at; end

    sig { params(value: T.nilable(Time)).returns(T.nilable(Time)) }
    def created_at=(value); end

    sig { returns(Integer) }
    def last_global_seq; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def last_global_seq=(value); end

    sig { returns(Integer) }
    def last_sequence; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def last_sequence=(value); end

    sig { returns(T.nilable(String)) }
    def reason; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def reason=(value); end

    sig { returns(String) }
    def state; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def state=(value); end

    sig { returns(T.nilable(Time)) }
    def state_changed_at; end

    sig { params(value: T.nilable(Time)).returns(T.nilable(Time)) }
    def state_changed_at=(value); end

    sig { returns(T.nilable(String)) }
    def transaction_id; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def transaction_id=(value); end

    sig { returns(Time) }
    def updated_at; end

    sig { params(value: T.nilable(Time)).returns(T.nilable(Time)) }
    def updated_at=(value); end
  end

  module GeneratedClassMethods
    sig { params(args: T.untyped).returns(T.nilable(::Models::TransferProjection)) }
    def [](*args); end

    sig { params(block: T.untyped).returns(T::Array[::Models::TransferProjection]) }
    def all(&block); end

    sig { params(args: T.untyped, block: T.untyped).returns(Integer) }
    def count(*args, &block); end

    sig do
      params(
        values: T::Hash[Symbol, T.untyped],
        block: T.nilable(T.proc.params(arg0: ::Models::TransferProjection).void)
      ).returns(::Models::TransferProjection)
    end
    def create(values = T.unsafe(nil), &block); end

    sig { returns(::Models::TransferProjection::PrivateDataset) }
    def dataset; end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def distinct(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def eager(*args, &block); end

    sig { returns(T::Boolean) }
    def empty?; end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def exclude(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def filter(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(T.nilable(::Models::TransferProjection)) }
    def first(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection) }
    def first!(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def for_update(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def group(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def group_by(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def having(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(T.nilable(::Models::TransferProjection)) }
    def last(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def limit(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def offset(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def order(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def order_by(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def reverse(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def select(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def select_append(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def where(*args, &block); end

    sig { params(pk: T.untyped).returns(T.nilable(::Models::TransferProjection)) }
    def with_pk(pk); end

    sig { params(pk: T.untyped).returns(::Models::TransferProjection) }
    def with_pk!(pk); end
  end

  module GeneratedDatasetMethods
    sig { params(block: T.untyped).returns(T::Array[::Models::TransferProjection]) }
    def all(&block); end

    sig { params(args: T.untyped, block: T.untyped).returns(Integer) }
    def count(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def distinct(*args, &block); end

    sig do
      params(
        block: T.proc.params(arg0: ::Models::TransferProjection).void
      ).returns(::Models::TransferProjection::PrivateDataset)
    end
    def each(&block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def eager(*args, &block); end

    sig { returns(T::Boolean) }
    def empty?; end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def exclude(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def filter(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(T.nilable(::Models::TransferProjection)) }
    def first(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection) }
    def first!(*args, &block); end

    sig do
      type_parameters(:U)
        .params(
          block: T.proc.params(arg0: ::Models::TransferProjection).returns(T.type_parameter(:U))
        ).returns(T::Array[T.type_parameter(:U)])
    end
    def flat_map(&block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def for_update(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def group(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def group_by(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def having(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(T.nilable(::Models::TransferProjection)) }
    def last(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def limit(*args, &block); end

    sig do
      type_parameters(:U)
        .params(
          block: T.proc.params(arg0: ::Models::TransferProjection).returns(T.type_parameter(:U))
        ).returns(T::Array[T.type_parameter(:U)])
    end
    def map(&block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def offset(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def order(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def order_by(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def reverse(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def select(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def select_append(*args, &block); end

    sig { returns(T.nilable(::Models::TransferProjection)) }
    def single_record; end

    sig { returns(T::Array[::Models::TransferProjection]) }
    def to_a; end

    sig { params(args: T.untyped, block: T.untyped).returns(::Models::TransferProjection::PrivateDataset) }
    def where(*args, &block); end

    sig { params(pk: T.untyped).returns(T.nilable(::Models::TransferProjection)) }
    def with_pk(pk); end

    sig { params(pk: T.untyped).returns(::Models::TransferProjection) }
    def with_pk!(pk); end
  end

  class PrivateDataset < ::Sequel::Dataset
    extend T::Generic
    include GeneratedDatasetMethods

    Elem = type_member { { fixed: ::Models::TransferProjection } }
  end
end
