# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `holidays` gem.
# Please instead update this file by running `bin/tapioca gem holidays`.


# FIXME This whole file is my next refactor target. We do wayyyyy too much by
#      convention here. We need hard and fast rules and explicit errors when you
#      try to parse something that isn't allowed. So if you are a dev recognize
#      that a lot of the guard statements in here are to codify existing legacy
#      logic. The fact is that we already require these guards, we just don't
#      enforce it explicitly. Now we will. And by doing so things will begin
#      to look very, very messy.
# This context builds a hash that contains {:year => [<array of months>]}. The idea is that
# we will iterate over each year and then over each month internally and check to see if the
# supplied dates match any holidays for the region and date. So if we supply start_date of 2015/1/1
# and end_date of 2015/6/1 then we will return a date driver of {:2015 => [0, 1, 2, 5, 6, 7]}.
# In the logic in the various other 'finder' contexts we will iterate over this and compare dates
# in these months to the supplied range to determine whether they should be returned to the user.
#
# pkg:gem/holidays#lib/holidays/definition/context/generator.rb:10
module Holidays
  class << self
    # pkg:gem/holidays#lib/holidays.rb:21
    def any_holidays_during_work_week?(date, *options); end

    # pkg:gem/holidays#lib/holidays.rb:88
    def available_regions; end

    # pkg:gem/holidays#lib/holidays.rb:34
    def between(start_date, end_date, *options); end

    # pkg:gem/holidays#lib/holidays.rb:81
    def cache_between(start_date, end_date, *options); end

    # pkg:gem/holidays#lib/holidays.rb:118
    def load_all; end

    # pkg:gem/holidays#lib/holidays.rb:100
    def load_custom(*files); end

    # FIXME All other methods start with a date and require a date. For the next
    #      major version bump we should take the opportunity to change this
    #      signature to match, e.g. next_holidays(from_date, count, options)
    #
    # pkg:gem/holidays#lib/holidays.rb:54
    def next_holidays(holidays_count, options, from_date = T.unsafe(nil)); end

    # pkg:gem/holidays#lib/holidays.rb:30
    def on(date, *options); end

    # pkg:gem/holidays#lib/holidays.rb:96
    def region_name(region); end

    # pkg:gem/holidays#lib/holidays.rb:92
    def region_names; end

    # FIXME All other methods start with a date and require a date. For the next
    #      major version bump we should take the opportunity to change this
    #      signature to match, e.g. year_holidays(from_date, options)
    #
    # pkg:gem/holidays#lib/holidays.rb:70
    def year_holidays(options, from_date = T.unsafe(nil)); end

    private

    # pkg:gem/holidays#lib/holidays.rb:133
    def get_date(date); end
  end
end

# Runs once at require time (see the bottom of lib/holidays.rb). Despite the
# historical name of its alias, this does NOT load per-region holiday data;
# that happens lazily in Definition::Context::Load. What it does:
#   1. Register the built-in calculation procs (easter, weekend modifiers,
#      lunar_to_solar, calculate_day_of_month) into custom_methods_repository.
#   2. Register the native per-region custom methods (CustomMethods.all).
#   3. Require generated_definitions/REGIONS.rb (the region-name list only).
#
# pkg:gem/holidays#lib/holidays/bootstrap.rb:11
class Holidays::Bootstrap
  class << self
    # pkg:gem/holidays#lib/holidays/bootstrap.rb:13
    def call; end

    private

    # pkg:gem/holidays#lib/holidays/bootstrap.rb:55
    def day_of_month_calculator; end

    # pkg:gem/holidays#lib/holidays/bootstrap.rb:43
    def gregorian_easter; end

    # pkg:gem/holidays#lib/holidays/bootstrap.rb:47
    def julian_easter; end

    # pkg:gem/holidays#lib/holidays/bootstrap.rb:59
    def lunar_date; end

    # pkg:gem/holidays#lib/holidays/bootstrap.rb:51
    def weekend_modifier; end
  end
end

# pkg:gem/holidays#lib/holidays.rb:15
Holidays::DAY_SYMBOLS = T.let(T.unsafe(nil), Array)

# pkg:gem/holidays#lib/holidays.rb:17
Holidays::DEFINITIONS_PATH = T.let(T.unsafe(nil), String)

# pkg:gem/holidays#lib/holidays/date_calculator/easter.rb:2
module Holidays::DateCalculator; end

# Calculate day of the month based on the week number and the day of the
# week.
#
# ==== Parameters
# [<tt>year</tt>]  Integer.
# [<tt>month</tt>] Integer from 1-12.
# [<tt>week</tt>]  One of <tt>:first</tt>, <tt>:second</tt>, <tt>:third</tt>,
#                  <tt>:fourth</tt>, <tt>:fifth</tt> or <tt>:last</tt>.
# [<tt>wday</tt>]  Day of the week as an integer from 0 (Sunday) to 6
#                  (Saturday) or as a symbol (e.g. <tt>:monday</tt>).
#
# Returns an integer.
#
# ===== Examples
# First Monday of January, 2008:
#   Holidays::Factory::DateCalculator.day_of_month_calculator.call(2008, 1, :first, :monday)
#   => 7
#
# Third Thursday of December, 2008:
#   Holidays::Factory::DateCalculator.day_of_month_calculator.call(2008, 12, :third, :thursday)
#   => 18
#
# Last Monday of January, 2008:
#   Holidays::Factory::DateCalculator.day_of_month_calculator.call(2008, 1, :last, 1)
#   => 28
# --
# see http://www.irt.org/articles/js050/index.htm
#
# pkg:gem/holidays#lib/holidays/date_calculator/day_of_month.rb:30
class Holidays::DateCalculator::DayOfMonth
  # pkg:gem/holidays#lib/holidays/date_calculator/day_of_month.rb:31
  def call(year, month, week, wday); end

  private

  # pkg:gem/holidays#lib/holidays/date_calculator/day_of_month.rb:59
  def day_symbols; end

  # pkg:gem/holidays#lib/holidays/date_calculator/day_of_month.rb:63
  def month_lengths; end

  # pkg:gem/holidays#lib/holidays/date_calculator/day_of_month.rb:55
  def weeks; end
end

# pkg:gem/holidays#lib/holidays/date_calculator/easter.rb:3
module Holidays::DateCalculator::Easter; end

# pkg:gem/holidays#lib/holidays/date_calculator/easter.rb:4
class Holidays::DateCalculator::Easter::Gregorian
  # pkg:gem/holidays#lib/holidays/date_calculator/easter.rb:5
  def calculate_easter_for(year); end

  # pkg:gem/holidays#lib/holidays/date_calculator/easter.rb:26
  def calculate_orthodox_easter_for(year); end
end

# pkg:gem/holidays#lib/holidays/date_calculator/easter.rb:47
class Holidays::DateCalculator::Easter::Julian
  # Copied from https://github.com/Loyolny/when_easter
  # Graciously allowed by Michał Nierebiński (https://github.com/Loyolny)
  #
  # pkg:gem/holidays#lib/holidays/date_calculator/easter.rb:50
  def calculate_easter_for(year); end

  # pkg:gem/holidays#lib/holidays/date_calculator/easter.rb:78
  def calculate_orthodox_easter_for(year); end
end

# Arithmetic ("tabular", a.k.a. Kuwaiti) Islamic calendar.
#
# Months alternate 30 and 29 days; leap years add a day to the twelfth
# month on a fixed 11-of-30 cycle. This is a purely arithmetic calendar,
# so it can land a day (occasionally two) either side of a locally
# proclaimed date. Callers that need the proclaimed date layer their own
# override table on top of this (see
# Holidays::Definition::CustomMethods::TR).
#
# pkg:gem/holidays#lib/holidays/date_calculator/hijri_date.rb:13
class Holidays::DateCalculator::HijriDate
  # Given a Gregorian year and a fixed Hijri month/day, return the
  # occurrence that falls within that Gregorian year, or nil if none does.
  #
  # A fixed Hijri date drifts ~11 days earlier each Gregorian year, so
  # roughly once every 33 years it falls twice in the same Gregorian year
  # (once in early January, once in late December). Only the earlier
  # occurrence is returned.
  #
  # pkg:gem/holidays#lib/holidays/date_calculator/hijri_date.rb:30
  def gregorian_year_occurrence(gregorian_year, hijri_month, hijri_day); end

  # pkg:gem/holidays#lib/holidays/date_calculator/hijri_date.rb:19
  def to_gregorian(hijri_year, hijri_month, hijri_day); end

  private

  # pkg:gem/holidays#lib/holidays/date_calculator/hijri_date.rb:43
  def to_jd(year, month, day); end
end

# Julian day number of 1 Muharram 1 AH minus one day, chosen so that
# to_jd's month/day terms are added directly. Corresponds to the civil
# epoch (Friday, 16 July 622 CE proleptic Julian).
#
# pkg:gem/holidays#lib/holidays/date_calculator/hijri_date.rb:17
Holidays::DateCalculator::HijriDate::EPOCH_JDN = T.let(T.unsafe(nil), Integer)

# Copied from https://github.com/sunsidew/ruby_lunardate
# Graciously allowed by JeeWoong Yang (https://github.com/sunsidew)
#
# pkg:gem/holidays#lib/holidays/date_calculator/lunar_date.rb:5
class Holidays::DateCalculator::LunarDate
  # pkg:gem/holidays#lib/holidays/date_calculator/lunar_date.rb:6
  def day; end

  # pkg:gem/holidays#lib/holidays/date_calculator/lunar_date.rb:6
  def day=(_arg0); end

  # pkg:gem/holidays#lib/holidays/date_calculator/lunar_date.rb:27
  def lunardays_for_type(month_type); end

  # pkg:gem/holidays#lib/holidays/date_calculator/lunar_date.rb:6
  def month; end

  # pkg:gem/holidays#lib/holidays/date_calculator/lunar_date.rb:6
  def month=(_arg0); end

  # pkg:gem/holidays#lib/holidays/date_calculator/lunar_date.rb:31
  def to_s; end

  # pkg:gem/holidays#lib/holidays/date_calculator/lunar_date.rb:8
  def to_solar(year, month, day, region); end

  # pkg:gem/holidays#lib/holidays/date_calculator/lunar_date.rb:6
  def year; end

  # pkg:gem/holidays#lib/holidays/date_calculator/lunar_date.rb:6
  def year=(_arg0); end
end

# Given the region, CALENDAR_YEAR_INFO_MAP looks up the date
# table and uses it in the calculation
#
# pkg:gem/holidays#lib/holidays/date_calculator/lunar_date.rb:501
Holidays::DateCalculator::LunarDate::CALENDAR_YEAR_INFO_MAP = T.let(T.unsafe(nil), Hash)

# Source: https://github.com/hungtcs/traditional-chinese-calendar-database/blob/master/database/all.json
#
# pkg:gem/holidays#lib/holidays/date_calculator/lunar_date.rb:344
Holidays::DateCalculator::LunarDate::CHINESE_LUNAR_YEAR_INFO = T.let(T.unsafe(nil), Array)

# pkg:gem/holidays#lib/holidays/date_calculator/lunar_date.rb:190
Holidays::DateCalculator::LunarDate::KOREAN_LUNAR_YEAR_INFO = T.let(T.unsafe(nil), Array)

# Provides number of days per lunar month type.  Lunar months
# can be either 29 or 30 days long (29.5 days, rounded up or down).
# Keys 3 - 6 provide data for intercalary (leap month) occurrences.
# Format: [TOTAL, NORMAL, LEAP]
#
# pkg:gem/holidays#lib/holidays/date_calculator/lunar_date.rb:513
Holidays::DateCalculator::LunarDate::LUNARDAYS_FOR_MONTHTYPE = T.let(T.unsafe(nil), Hash)

# pkg:gem/holidays#lib/holidays/date_calculator/lunar_date.rb:497
Holidays::DateCalculator::LunarDate::MAX_YEAR_NUMBER = T.let(T.unsafe(nil), Integer)

# Provides the reference point for the Gregorian calendar and is
# used in all calculations
#
# pkg:gem/holidays#lib/holidays/date_calculator/lunar_date.rb:524
Holidays::DateCalculator::LunarDate::SOLAR_START_DATE = T.let(T.unsafe(nil), Date)

# pkg:gem/holidays#lib/holidays/date_calculator/lunar_date.rb:37
Holidays::DateCalculator::LunarDate::VIETNAMESE_LUNAR_YEAR_INFO = T.let(T.unsafe(nil), Array)

# pkg:gem/holidays#lib/holidays/date_calculator/weekend_modifier.rb:3
class Holidays::DateCalculator::WeekendModifier
  # Move date to Monday if it occurs on a Sunday.
  # Does not modify the date if it is not a Sunday.
  # Used as a callback function.
  #
  # pkg:gem/holidays#lib/holidays/date_calculator/weekend_modifier.rb:15
  def to_monday_if_sunday(date); end

  # Move date to Monday if it occurs on a Saturday on Sunday.
  # Does not modify date if it is not a weekend.
  # Used as a callback function.
  #
  # pkg:gem/holidays#lib/holidays/date_calculator/weekend_modifier.rb:7
  def to_monday_if_weekend(date); end

  # Finds the next weekday. For example, if a 'Friday' date is received
  # it will return the following Monday. If Sunday then return Monday,
  # if Saturday return Monday, if Tuesday return Wednesday, etc.
  #
  # pkg:gem/holidays#lib/holidays/date_calculator/weekend_modifier.rb:74
  def to_next_weekday(date); end

  # pkg:gem/holidays#lib/holidays/date_calculator/weekend_modifier.rb:95
  def to_previous_day_if_leap_year(date); end

  # pkg:gem/holidays#lib/holidays/date_calculator/weekend_modifier.rb:24
  def to_the_second_weekday_after(date); end

  # pkg:gem/holidays#lib/holidays/date_calculator/weekend_modifier.rb:20
  def to_the_weekday_after(date); end

  # if Christmas falls on a Saturday, move it to the next Monday (Boxing Day will be Sunday and potentially Tuesday)
  # if Christmas falls on a Sunday, move it to the next Tuesday (Boxing Day will go on Monday)
  #
  # if Boxing Day falls on a Saturday, move it to the next Monday (Christmas will go on Friday)
  # if Boxing Day falls on a Sunday, move it to the next Tuesday (Christmas will go on Saturday & Monday)
  #
  # pkg:gem/holidays#lib/holidays/date_calculator/weekend_modifier.rb:45
  def to_tuesday_if_sunday_or_monday_if_saturday(date); end

  # Move Boxing Day if it falls on a weekend, leaving room for Christmas.
  # Used as a callback function.
  #
  # pkg:gem/holidays#lib/holidays/date_calculator/weekend_modifier.rb:30
  def to_weekday_if_boxing_weekend(date); end

  # Call to_weekday_if_boxing_weekend but first get date based on year
  # Used as a callback function.
  #
  # pkg:gem/holidays#lib/holidays/date_calculator/weekend_modifier.rb:58
  def to_weekday_if_boxing_weekend_from_year(year); end

  # Call to_weekday_if_boxing_weekend but first get date based on year
  # Used as a callback function.
  #
  # pkg:gem/holidays#lib/holidays/date_calculator/weekend_modifier.rb:52
  def to_weekday_if_boxing_weekend_from_year_or_to_tuesday_if_monday(year); end

  # Move date to Monday if it occurs on a Sunday or to Friday if it occurs on a
  # Saturday.
  # Used as a callback function.
  #
  # pkg:gem/holidays#lib/holidays/date_calculator/weekend_modifier.rb:65
  def to_weekday_if_weekend(date); end
end

# pkg:gem/holidays#lib/holidays/definition/context/generator.rb:11
module Holidays::Definition; end

# pkg:gem/holidays#lib/holidays/definition/context/generator.rb:12
module Holidays::Definition::Context; end

# pkg:gem/holidays#lib/holidays/definition/context/function_processor.rb:6
class Holidays::Definition::Context::FunctionProcessor
  # pkg:gem/holidays#lib/holidays/definition/context/function_processor.rb:7
  def initialize(custom_methods_repo, proc_result_cache_repo); end

  # pkg:gem/holidays#lib/holidays/definition/context/function_processor.rb:12
  def call(input, func_id, desired_func_args, func_modifier = T.unsafe(nil)); end

  private

  # pkg:gem/holidays#lib/holidays/definition/context/function_processor.rb:53
  def calculate(input, id, args, modifier); end

  # Arguments are supplied in the order the definition declares them. The proc
  # is built with that same declared order, so anything else silently binds
  # values to the wrong parameters.
  #
  # pkg:gem/holidays#lib/holidays/definition/context/function_processor.rb:41
  def parse_arguments(input, target_args); end

  # pkg:gem/holidays#lib/holidays/definition/context/function_processor.rb:25
  def validate!(input, func_id, desired_func_args); end
end

# pkg:gem/holidays#lib/holidays/definition/context/function_processor.rb:23
Holidays::Definition::Context::FunctionProcessor::VALID_ARGUMENTS = T.let(T.unsafe(nil), Array)

# pkg:gem/holidays#lib/holidays/definition/context/generator.rb:13
class Holidays::Definition::Context::Generator
  # pkg:gem/holidays#lib/holidays/definition/context/generator.rb:14
  def initialize(custom_method_parser, custom_method_source_decorator, custom_methods_repository, test_parser, test_source_generator, module_source_generator); end

  # pkg:gem/holidays#lib/holidays/definition/context/generator.rb:70
  def generate_definition_source(module_name, files, regions, rules_by_month, custom_methods, tests); end

  # pkg:gem/holidays#lib/holidays/definition/context/generator.rb:23
  def parse_definition_files(files); end

  private

  # FIXME This should really be split out and tested with its own unit tests.
  #
  # pkg:gem/holidays#lib/holidays/definition/context/generator.rb:149
  def generate_month_definition_strings(rules_by_month, parsed_custom_methods); end

  # This method sucks. The issue here is that the custom methods repo has the 'general' methods (like easter)
  # but the 'parsed_custom_methods' have the recently parsed stuff. We don't load those until they are needed later.
  # This entire file is a refactor target so I am adding some tech debt to get me over the hump.
  # What we should do is ensure that all custom methods are loaded into the repo as soon as they are parsed
  # so we only have one place to look.
  #
  # pkg:gem/holidays#lib/holidays/definition/context/generator.rb:212
  def get_function_arguments(function_id, parsed_custom_methods); end

  # FIXME This should be a 'month_definitions_parser' like the above parser
  #
  # pkg:gem/holidays#lib/holidays/definition/context/generator.rb:88
  def parse_month_definitions(month_definitions, parsed_custom_methods); end
end

# pkg:gem/holidays#lib/holidays/definition/context/load.rb:4
class Holidays::Definition::Context::Load
  # pkg:gem/holidays#lib/holidays/definition/context/load.rb:5
  def initialize(definition_merger, full_definitions_path); end

  # pkg:gem/holidays#lib/holidays/definition/context/load.rb:10
  def call(region); end
end

# Merge a new set of definitions into the Holidays module.
#
# pkg:gem/holidays#lib/holidays/definition/context/merger.rb:5
class Holidays::Definition::Context::Merger
  # pkg:gem/holidays#lib/holidays/definition/context/merger.rb:6
  def initialize(holidays_by_month_repo, regions_repo, custom_methods_repo, cache_repo, proc_result_cache_repo); end

  # pkg:gem/holidays#lib/holidays/definition/context/merger.rb:14
  def call(target_regions, target_holidays, target_custom_methods, target_custom_method_sources = T.unsafe(nil)); end

  private

  # Builds a map of {func_id => [regions]} from the holiday definitions
  # so the custom_methods repo knows which regions each function belongs to.
  #
  # pkg:gem/holidays#lib/holidays/definition/context/merger.rb:31
  def derive_function_regions(holidays_by_month); end
end

# pkg:gem/holidays#lib/holidays/definition/custom_methods/ar.rb:5
module Holidays::Definition::CustomMethods
  class << self
    # Maps the full call-signature string used by YAML +function:+/+observed:+
    # references to the native proc that implements it. Seeded into
    # Factory::Definition.custom_methods_repository at boot by
    # Holidays::Bootstrap.call, alongside the global built-in methods.
    #
    # Native replacement for the old per-region +methods:/ruby:+ YAML blocks.
    # No eval, no public registration API.
    #
    # ca_victoria_day and day_after_thanksgiving each have byte-identical
    # duplicates in other region YAML files; hosted once here and shared.
    #
    # pkg:gem/holidays#lib/holidays/definition/custom_methods/registry.rb:35
    def all; end
  end
end

# ar custom holiday calculations, ported verbatim from the
# +methods:+ block in definitions/ar.yaml.
#
# pkg:gem/holidays#lib/holidays/definition/custom_methods/ar.rb:8
module Holidays::Definition::CustomMethods::AR
  class << self
    # pkg:gem/holidays#lib/holidays/definition/custom_methods/ar.rb:10
    def to_nearest_monday(date); end
  end
end

# au custom holiday calculations, ported verbatim from the
# +methods:+ block in definitions/au.yaml.
#
# pkg:gem/holidays#lib/holidays/definition/custom_methods/au.rb:8
module Holidays::Definition::CustomMethods::AU
  class << self
    # pkg:gem/holidays#lib/holidays/definition/custom_methods/au.rb:10
    def afl_grand_final(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/au.rb:51
    def hobart_show_day(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/au.rb:56
    def march_pub_hol_sa(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/au.rb:60
    def may_pub_hol_sa(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/au.rb:64
    def qld_brisbane_ekka_holiday(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/au.rb:35
    def qld_kings_bday_october(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/au.rb:43
    def qld_labour_day_may(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/au.rb:47
    def qld_labour_day_october(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/au.rb:31
    def qld_queens_bday_october(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/au.rb:39
    def qld_queens_birthday_june(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/au.rb:75
    def to_nearest_monday_after(date); end
  end
end

# ca custom holiday calculations, ported verbatim from the
# +methods:+ block in definitions/ca.yaml.
#
# pkg:gem/holidays#lib/holidays/definition/custom_methods/ca.rb:8
module Holidays::Definition::CustomMethods::CA
  class << self
    # pkg:gem/holidays#lib/holidays/definition/custom_methods/ca.rb:10
    def ca_victoria_day(year); end
  end
end

# ch custom holiday calculations, ported verbatim from the
# +methods:+ block in definitions/ch.yaml.
#
# pkg:gem/holidays#lib/holidays/definition/custom_methods/ch.rb:8
module Holidays::Definition::CustomMethods::CH
  class << self
    # pkg:gem/holidays#lib/holidays/definition/custom_methods/ch.rb:44
    def ch_be_zibelemaerit(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/ch.rb:21
    def ch_ge_jeune_genevois(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/ch.rb:31
    def ch_gl_naefelser_fahrt(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/ch.rb:10
    def ch_vd_lundi_du_jeune_federal(year); end
  end
end

# cl custom holiday calculations, ported verbatim from the
# +methods:+ block in definitions/cl.yaml.
#
# pkg:gem/holidays#lib/holidays/definition/custom_methods/cl.rb:8
module Holidays::Definition::CustomMethods::CL
  class << self
    # pkg:gem/holidays#lib/holidays/definition/custom_methods/cl.rb:20
    def columbus_day_cl(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/cl.rb:30
    def other_churches_day_cl(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/cl.rb:10
    def st_peter_st_paul_cl(year); end
  end
end

# cn custom holiday calculations, ported verbatim from the
# +methods:+ block in definitions/cn.yaml.
#
# pkg:gem/holidays#lib/holidays/definition/custom_methods/cn.rb:8
module Holidays::Definition::CustomMethods::CN
  class << self
    # Qingming falls when the sun reaches celestial longitude 15 degrees,
    # which lands on 4 or 5 April. This is the standard solar-term
    # approximation; the century constant shifts between the 20th and
    # 21st centuries.
    #
    # pkg:gem/holidays#lib/holidays/definition/custom_methods/cn.rb:14
    def cn_qingming(year); end
  end
end

# co custom holiday calculations, ported verbatim from the
# +methods:+ block in definitions/co.yaml.
#
# pkg:gem/holidays#lib/holidays/definition/custom_methods/co.rb:8
module Holidays::Definition::CustomMethods::CO
  class << self
    # pkg:gem/holidays#lib/holidays/definition/custom_methods/co.rb:10
    def to_following_monday_if_not_monday(date); end
  end
end

# de custom holiday calculations, ported verbatim from the
# +methods:+ block in definitions/de.yaml.
#
# pkg:gem/holidays#lib/holidays/definition/custom_methods/de.rb:8
module Holidays::Definition::CustomMethods::DE
  class << self
    # pkg:gem/holidays#lib/holidays/definition/custom_methods/de.rb:10
    def de_buss_und_bettag(year); end
  end
end

# fedex custom holiday calculations, ported verbatim from the
# +methods:+ block in definitions/fedex.yaml.
#
# pkg:gem/holidays#lib/holidays/definition/custom_methods/fedex.rb:8
module Holidays::Definition::CustomMethods::FEDEX
  class << self
    # pkg:gem/holidays#lib/holidays/definition/custom_methods/fedex.rb:10
    def day_after_thanksgiving(year); end
  end
end

# fi custom holiday calculations, ported verbatim from the
# +methods:+ block in definitions/fi.yaml.
#
# pkg:gem/holidays#lib/holidays/definition/custom_methods/fi.rb:8
module Holidays::Definition::CustomMethods::FI
  class << self
    # pkg:gem/holidays#lib/holidays/definition/custom_methods/fi.rb:10
    def fi_juhannusaatto(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/fi.rb:20
    def fi_juhannuspaiva(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/fi.rb:26
    def fi_pyhainpaiva(year); end
  end
end

# ie custom holiday calculations, ported verbatim from the
# +methods:+ block in definitions/ie.yaml.
#
# pkg:gem/holidays#lib/holidays/definition/custom_methods/ie.rb:8
module Holidays::Definition::CustomMethods::IE
  class << self
    # pkg:gem/holidays#lib/holidays/definition/custom_methods/ie.rb:10
    def ie_st_brigids_day(year); end
  end
end

# is custom holiday calculations, ported verbatim from the
# +methods:+ block in definitions/is.yaml.
#
# pkg:gem/holidays#lib/holidays/definition/custom_methods/is.rb:8
module Holidays::Definition::CustomMethods::IS
  class << self
    # pkg:gem/holidays#lib/holidays/definition/custom_methods/is.rb:10
    def is_sumardagurinn_fyrsti(year); end
  end
end

# jp custom holiday calculations, ported verbatim from the
# +methods:+ block in definitions/jp.yaml.
#
# pkg:gem/holidays#lib/holidays/definition/custom_methods/jp.rb:8
module Holidays::Definition::CustomMethods::JP
  class << self
    # pkg:gem/holidays#lib/holidays/definition/custom_methods/jp.rb:66
    def jp_citizens_holiday(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/jp.rb:10
    def jp_health_sports_day_substitute(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/jp.rb:38
    def jp_marine_day_substitute(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/jp.rb:75
    def jp_mountain_holiday(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/jp.rb:79
    def jp_mountain_holiday_substitute(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/jp.rb:42
    def jp_national_culture_day(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/jp.rb:61
    def jp_national_culture_day_substitute(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/jp.rb:93
    def jp_next_weekday(date); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/jp.rb:84
    def jp_respect_for_aged_holiday_substitute(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/jp.rb:88
    def jp_substitute_holiday(year, month, day); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/jp.rb:14
    def jp_vernal_equinox_day(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/jp.rb:33
    def jp_vernal_equinox_day_substitute(year); end
  end
end

# kr custom holiday calculations, ported verbatim from the
# +methods:+ block in definitions/kr.yaml.
#
# pkg:gem/holidays#lib/holidays/definition/custom_methods/kr.rb:6
module Holidays::Definition::CustomMethods::KR
  class << self
    # Seollal eve is the day before Seollal (Korean New Year), which is
    # the first day of the first lunar month.
    #
    # pkg:gem/holidays#lib/holidays/definition/custom_methods/kr.rb:10
    def kr_seollal_eve(year, region); end
  end
end

# lv custom holiday calculations, ported verbatim from the
# +methods:+ block in definitions/lv.yaml.
#
# pkg:gem/holidays#lib/holidays/definition/custom_methods/lv.rb:8
module Holidays::Definition::CustomMethods::LV
  class << self
    # pkg:gem/holidays#lib/holidays/definition/custom_methods/lv.rb:10
    def lv_song_and_dance_festival_end_date(year); end
  end
end

# nz custom holiday calculations, ported verbatim from the
# +methods:+ block in definitions/nz.yaml.
#
# pkg:gem/holidays#lib/holidays/definition/custom_methods/nz.rb:8
module Holidays::Definition::CustomMethods::NZ
  class << self
    # pkg:gem/holidays#lib/holidays/definition/custom_methods/nz.rb:10
    def closest_monday(date); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/nz.rb:37
    def matariki(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/nz.rb:25
    def next_week(date); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/nz.rb:29
    def nz_canterbury_anniversary(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/nz.rb:21
    def previous_friday(date); end
  end
end

# ph custom holiday calculations, ported verbatim from the
# +methods:+ block in definitions/ph.yaml.
#
# pkg:gem/holidays#lib/holidays/definition/custom_methods/ph.rb:8
module Holidays::Definition::CustomMethods::PH
  class << self
    # pkg:gem/holidays#lib/holidays/definition/custom_methods/ph.rb:10
    def ph_heroes_day(year); end
  end
end

# se custom holiday calculations, ported verbatim from the
# +methods:+ block in definitions/se.yaml.
#
# pkg:gem/holidays#lib/holidays/definition/custom_methods/se.rb:8
module Holidays::Definition::CustomMethods::SE
  class << self
    # pkg:gem/holidays#lib/holidays/definition/custom_methods/se.rb:16
    def se_alla_helgons_dag(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/se.rb:10
    def se_midsommardagen(year); end
  end
end

# tr custom holiday calculations.
#
# Ramazan Bayramı is 1 Shawwal and Kurban Bayramı is 10 Dhul-Hijjah of
# the Hijri calendar. Both are derived from the arithmetic Islamic
# calendar (Holidays::DateCalculator::HijriDate). The civil holidays are
# proclaimed by Türkiye's Diyanet and in most years so far have landed a
# day (2016 Ramazan Bayramı, two days) before the arithmetic result;
# DIYANET_OVERRIDES pins those years to the proclaimed date. Years with
# no entry fall back to the calculation. See definitions#377.
#
# pkg:gem/holidays#lib/holidays/definition/custom_methods/tr.rb:15
module Holidays::Definition::CustomMethods::TR
  class << self
    # pkg:gem/holidays#lib/holidays/definition/custom_methods/tr.rb:50
    def ramadan_feast(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/tr.rb:54
    def sacrifice_feast(year); end

    private

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/tr.rb:60
    def feast(name, year, hijri_month, hijri_day); end
  end
end

# pkg:gem/holidays#lib/holidays/definition/custom_methods/tr.rb:17
Holidays::Definition::CustomMethods::TR::DHU_AL_HIJJAH = T.let(T.unsafe(nil), Integer)

# Proclaimed first days that differ from the arithmetic calendar,
# keyed by [feast, gregorian_year]. Sourced from the Diyanet dates
# that the definition file previously carried as a fixed table, plus
# https://vakithesaplama.diyanet.gov.tr/resmitatiller.php for 2021-2030.
#
# pkg:gem/holidays#lib/holidays/definition/custom_methods/tr.rb:23
Holidays::Definition::CustomMethods::TR::DIYANET_OVERRIDES = T.let(T.unsafe(nil), Hash)

# pkg:gem/holidays#lib/holidays/definition/custom_methods/tr.rb:16
Holidays::Definition::CustomMethods::TR::SHAWWAL = T.let(T.unsafe(nil), Integer)

# us custom holiday calculations, ported verbatim from the
# +methods:+ block in definitions/us.yaml.
#
# pkg:gem/holidays#lib/holidays/definition/custom_methods/us.rb:8
module Holidays::Definition::CustomMethods::US
  class << self
    # pkg:gem/holidays#lib/holidays/definition/custom_methods/us.rb:10
    def christmas_eve_holiday(date); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/us.rb:102
    def election_day(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/us.rb:106
    def even_year_election_day(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/us.rb:41
    def georgia_state_holiday(year, month); end

    # Independence Day observed shift, which varies by region:
    #   - us_ri: Rhode Island moves to the following Monday on a weekend
    #     (Saturday -> +2, Sunday -> +1).
    #   - us_tx: Texas does not shift, the date is returned unchanged.
    #   - everyone else: nearest weekday, same as +to_weekday_if_weekend+
    #     (Saturday -> Friday, Sunday -> Monday).
    #
    # pkg:gem/holidays#lib/holidays/definition/custom_methods/us.rb:81
    def independence_day(region, date); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/us.rb:54
    def juneteenth_national_independence_day(region, date); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/us.rb:47
    def lee_jackson_day(year, month); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/us.rb:15
    def rosh_hashanah(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/us.rb:112
    def us_inauguration_day(year); end

    # pkg:gem/holidays#lib/holidays/definition/custom_methods/us.rb:28
    def yom_kippur(year); end
  end
end

# pkg:gem/holidays#lib/holidays/definition/decorator/custom_method_proc.rb:3
module Holidays::Definition::Decorator; end

# pkg:gem/holidays#lib/holidays/definition/decorator/custom_method_proc.rb:4
class Holidays::Definition::Decorator::CustomMethodProc
  # pkg:gem/holidays#lib/holidays/definition/decorator/custom_method_proc.rb:5
  def call(proc); end

  private

  # pkg:gem/holidays#lib/holidays/definition/decorator/custom_method_proc.rb:21
  def parse_arguments(args); end

  # pkg:gem/holidays#lib/holidays/definition/decorator/custom_method_proc.rb:15
  def validate!(proc); end
end

# pkg:gem/holidays#lib/holidays/definition/decorator/custom_method_source.rb:4
class Holidays::Definition::Decorator::CustomMethodSource
  # pkg:gem/holidays#lib/holidays/definition/decorator/custom_method_source.rb:5
  def call(proc); end

  private

  # pkg:gem/holidays#lib/holidays/definition/decorator/custom_method_source.rb:23
  def args_string(args); end

  # pkg:gem/holidays#lib/holidays/definition/decorator/custom_method_source.rb:17
  def validate!(proc); end
end

# pkg:gem/holidays#lib/holidays/definition/decorator/test.rb:4
class Holidays::Definition::Decorator::Test
  # pkg:gem/holidays#lib/holidays/definition/decorator/test.rb:5
  def call(t); end

  private

  # pkg:gem/holidays#lib/holidays/definition/decorator/test.rb:29
  def decorate_options(options); end
end

# pkg:gem/holidays#lib/holidays/definition/entity/custom_method.rb:3
module Holidays::Definition::Entity; end

# pkg:gem/holidays#lib/holidays/definition/entity/custom_method.rb:4
class Holidays::Definition::Entity::CustomMethod < ::Struct
  # pkg:gem/holidays#lib/holidays/definition/entity/custom_method.rb:5
  def initialize(fields = T.unsafe(nil)); end

  # pkg:gem/holidays#lib/holidays/definition/entity/custom_method.rb:4
  def arguments; end

  # pkg:gem/holidays#lib/holidays/definition/entity/custom_method.rb:4
  def arguments=(_); end

  # pkg:gem/holidays#lib/holidays/definition/entity/custom_method.rb:4
  def name; end

  # pkg:gem/holidays#lib/holidays/definition/entity/custom_method.rb:4
  def name=(_); end

  # pkg:gem/holidays#lib/holidays/definition/entity/custom_method.rb:4
  def source; end

  # pkg:gem/holidays#lib/holidays/definition/entity/custom_method.rb:4
  def source=(_); end

  class << self
    # pkg:gem/holidays#lib/holidays/definition/entity/custom_method.rb:4
    def [](*_arg0); end

    # pkg:gem/holidays#lib/holidays/definition/entity/custom_method.rb:4
    def inspect; end

    # pkg:gem/holidays#lib/holidays/definition/entity/custom_method.rb:4
    def keyword_init?; end

    # pkg:gem/holidays#lib/holidays/definition/entity/custom_method.rb:4
    def members; end

    # pkg:gem/holidays#lib/holidays/definition/entity/custom_method.rb:4
    def new(*_arg0); end
  end
end

# pkg:gem/holidays#lib/holidays/definition/entity/test.rb:4
class Holidays::Definition::Entity::Test < ::Struct
  # pkg:gem/holidays#lib/holidays/definition/entity/test.rb:5
  def initialize(fields = T.unsafe(nil)); end

  # pkg:gem/holidays#lib/holidays/definition/entity/test.rb:4
  def dates; end

  # pkg:gem/holidays#lib/holidays/definition/entity/test.rb:4
  def dates=(_); end

  # pkg:gem/holidays#lib/holidays/definition/entity/test.rb:4
  def holiday?; end

  # pkg:gem/holidays#lib/holidays/definition/entity/test.rb:4
  def name; end

  # pkg:gem/holidays#lib/holidays/definition/entity/test.rb:4
  def name=(_); end

  # pkg:gem/holidays#lib/holidays/definition/entity/test.rb:4
  def options; end

  # pkg:gem/holidays#lib/holidays/definition/entity/test.rb:4
  def options=(_); end

  # pkg:gem/holidays#lib/holidays/definition/entity/test.rb:4
  def regions; end

  # pkg:gem/holidays#lib/holidays/definition/entity/test.rb:4
  def regions=(_); end

  class << self
    # pkg:gem/holidays#lib/holidays/definition/entity/test.rb:4
    def [](*_arg0); end

    # pkg:gem/holidays#lib/holidays/definition/entity/test.rb:4
    def inspect; end

    # pkg:gem/holidays#lib/holidays/definition/entity/test.rb:4
    def keyword_init?; end

    # pkg:gem/holidays#lib/holidays/definition/entity/test.rb:4
    def members; end

    # pkg:gem/holidays#lib/holidays/definition/entity/test.rb:4
    def new(*_arg0); end
  end
end

# pkg:gem/holidays#lib/holidays/definition/generator/module.rb:5
module Holidays::Definition::Generator; end

# pkg:gem/holidays#lib/holidays/definition/generator/module.rb:6
class Holidays::Definition::Generator::Module
  # NOTE: +custom_methods+ is accepted for backwards-compatible call sites but is
  # no longer baked into the generated module. Per-region custom methods are now
  # hosted natively under lib/holidays/definition/custom_methods/ and seeded into
  # the repository at boot. YAML files that still carry methods:/ruby: blocks are
  # tolerated: their bodies are simply ignored here.
  #
  # pkg:gem/holidays#lib/holidays/definition/generator/module.rb:12
  def call(module_name, files, regions, month_strings, custom_methods = T.unsafe(nil)); end
end

# pkg:gem/holidays#lib/holidays/definition/generator/regions.rb:4
class Holidays::Definition::Generator::Regions
  # pkg:gem/holidays#lib/holidays/definition/generator/regions.rb:9
  def call(regions, region_names = T.unsafe(nil)); end

  private

  # pkg:gem/holidays#lib/holidays/definition/generator/regions.rb:42
  def generate_parent_lookup(regions); end

  # Symbol keys and string values are emitted via inspect so the literal
  # round-trips exactly: YAML-reserved keys like :no stay symbols and
  # values with quotes or commas are escaped rather than breaking the hash.
  #
  # pkg:gem/holidays#lib/holidays/definition/generator/regions.rb:59
  def generate_region_names(region_names); end

  # pkg:gem/holidays#lib/holidays/definition/generator/regions.rb:32
  def to_array(regions); end

  # pkg:gem/holidays#lib/holidays/definition/generator/regions.rb:26
  def validate!(regions); end
end

# The "ca", "mx", and "us" holiday definitions include the "northamericainformal"
# holiday definitions, but that does not make these countries subregions of one another.
#
# pkg:gem/holidays#lib/holidays/definition/generator/regions.rb:7
Holidays::Definition::Generator::Regions::NORTH_AMERICA_REGIONS = T.let(T.unsafe(nil), Array)

# pkg:gem/holidays#lib/holidays/definition/generator/test.rb:6
class Holidays::Definition::Generator::Test
  # pkg:gem/holidays#lib/holidays/definition/generator/test.rb:7
  def initialize(decorator); end

  # pkg:gem/holidays#lib/holidays/definition/generator/test.rb:11
  def call(module_name, file_names, tests); end

  private

  # pkg:gem/holidays#lib/holidays/definition/generator/test.rb:39
  def decorate(tests); end

  # pkg:gem/holidays#lib/holidays/definition/generator/test.rb:33
  def validate!(module_name, file_names, tests); end
end

# pkg:gem/holidays#lib/holidays/definition/parser/custom_method.rb:5
module Holidays::Definition::Parser; end

# pkg:gem/holidays#lib/holidays/definition/parser/custom_method.rb:6
class Holidays::Definition::Parser::CustomMethod
  # pkg:gem/holidays#lib/holidays/definition/parser/custom_method.rb:7
  def initialize(validator); end

  # pkg:gem/holidays#lib/holidays/definition/parser/custom_method.rb:11
  def call(methods); end

  private

  # pkg:gem/holidays#lib/holidays/definition/parser/custom_method.rb:60
  def args_string(args); end

  # pkg:gem/holidays#lib/holidays/definition/parser/custom_method.rb:56
  def method_key(name, args); end

  # pkg:gem/holidays#lib/holidays/definition/parser/custom_method.rb:45
  def parse_arguments!(arguments); end

  # pkg:gem/holidays#lib/holidays/definition/parser/custom_method.rb:33
  def validate!(methods); end
end

# pkg:gem/holidays#lib/holidays/definition/parser/test.rb:6
class Holidays::Definition::Parser::Test
  # pkg:gem/holidays#lib/holidays/definition/parser/test.rb:7
  def initialize(validator); end

  # pkg:gem/holidays#lib/holidays/definition/parser/test.rb:11
  def call(tests); end

  private

  # If flag is not present then default to 'true'
  #
  # pkg:gem/holidays#lib/holidays/definition/parser/test.rb:80
  def is_holiday?(flag); end

  # pkg:gem/holidays#lib/holidays/definition/parser/test.rb:51
  def parse_dates(dates); end

  # pkg:gem/holidays#lib/holidays/definition/parser/test.rb:67
  def parse_options(options); end

  # pkg:gem/holidays#lib/holidays/definition/parser/test.rb:61
  def parse_regions(regions); end

  # pkg:gem/holidays#lib/holidays/definition/parser/test.rb:32
  def validate!(tests); end
end

# pkg:gem/holidays#lib/holidays/definition/repository/holidays_by_month.rb:3
module Holidays::Definition::Repository; end

# pkg:gem/holidays#lib/holidays/definition/repository/cache.rb:4
class Holidays::Definition::Repository::Cache
  # pkg:gem/holidays#lib/holidays/definition/repository/cache.rb:5
  def initialize; end

  # pkg:gem/holidays#lib/holidays/definition/repository/cache.rb:9
  def cache_between(start_date, end_date, cache_data, options); end

  # pkg:gem/holidays#lib/holidays/definition/repository/cache.rb:18
  def find(start_date, end_date, options); end

  # pkg:gem/holidays#lib/holidays/definition/repository/cache.rb:31
  def reset!; end

  private

  # pkg:gem/holidays#lib/holidays/definition/repository/cache.rb:42
  def in_cache_range?(start_date, end_date, options); end

  # pkg:gem/holidays#lib/holidays/definition/repository/cache.rb:38
  def normalize(options); end
end

# pkg:gem/holidays#lib/holidays/definition/repository/custom_methods.rb:4
class Holidays::Definition::Repository::CustomMethods
  # pkg:gem/holidays#lib/holidays/definition/repository/custom_methods.rb:5
  def initialize; end

  # When a conflict is detected the method is stored as a regional override keyed by its regions.
  # find() then resolves the right implementation at lookup time using the queried region.
  #
  # pkg:gem/holidays#lib/holidays/definition/repository/custom_methods.rb:13
  def add(new_custom_methods, new_sources = T.unsafe(nil), function_regions = T.unsafe(nil)); end

  # Returns the proc for the given method_id.
  #
  # When a region is supplied, regional overrides are checked first so
  # that conflicting methods with the same name but different logic each
  # resolve to their own implementation.
  #
  # pkg:gem/holidays#lib/holidays/definition/repository/custom_methods.rb:42
  def find(method_id, region = T.unsafe(nil)); end
end

# pkg:gem/holidays#lib/holidays/definition/repository/holidays_by_month.rb:4
class Holidays::Definition::Repository::HolidaysByMonth
  # pkg:gem/holidays#lib/holidays/definition/repository/holidays_by_month.rb:5
  def initialize; end

  # pkg:gem/holidays#lib/holidays/definition/repository/holidays_by_month.rb:18
  def add(new_holidays); end

  # pkg:gem/holidays#lib/holidays/definition/repository/holidays_by_month.rb:9
  def all; end

  # pkg:gem/holidays#lib/holidays/definition/repository/holidays_by_month.rb:13
  def find_by_month(month); end

  private

  # pkg:gem/holidays#lib/holidays/definition/repository/holidays_by_month.rb:43
  def definition_exists?(existing_def, target_def); end
end

# ==== Benchmarks
#
# Lookup Easter Sunday, with caching, by number of iterations:
#
#       user     system      total        real
# 0001  0.000000   0.000000   0.000000 (  0.000000)
# 0010  0.000000   0.000000   0.000000 (  0.000000)
# 0100  0.078000   0.000000   0.078000 (  0.078000)
# 1000  0.641000   0.000000   0.641000 (  0.641000)
# 5000  3.172000   0.015000   3.187000 (  3.219000)
#
# Lookup Easter Sunday, without caching, by number of iterations:
#
#       user     system      total        real
# 0001  0.000000   0.000000   0.000000 (  0.000000)
# 0010  0.016000   0.000000   0.016000 (  0.016000)
# 0100  0.125000   0.000000   0.125000 (  0.125000)
# 1000  1.234000   0.000000   1.234000 (  1.234000)
# 5000  6.094000   0.031000   6.125000 (  6.141000)
#
# pkg:gem/holidays#lib/holidays/definition/repository/proc_result_cache.rb:23
class Holidays::Definition::Repository::ProcResultCache
  # pkg:gem/holidays#lib/holidays/definition/repository/proc_result_cache.rb:24
  def initialize; end

  # pkg:gem/holidays#lib/holidays/definition/repository/proc_result_cache.rb:28
  def lookup(function, *function_arguments); end

  # pkg:gem/holidays#lib/holidays/definition/repository/proc_result_cache.rb:36
  def reset!; end

  private

  # pkg:gem/holidays#lib/holidays/definition/repository/proc_result_cache.rb:49
  def build_proc_key(function, function_arguments); end

  # pkg:gem/holidays#lib/holidays/definition/repository/proc_result_cache.rb:42
  def validate!(function, function_arguments); end
end

# pkg:gem/holidays#lib/holidays/definition/repository/regions.rb:4
class Holidays::Definition::Repository::Regions
  # pkg:gem/holidays#lib/holidays/definition/repository/regions.rb:5
  def initialize(all_generated_regions, parent_region_lookup); end

  # pkg:gem/holidays#lib/holidays/definition/repository/regions.rb:28
  def add(regions); end

  # pkg:gem/holidays#lib/holidays/definition/repository/regions.rb:11
  def all_generated; end

  # pkg:gem/holidays#lib/holidays/definition/repository/regions.rb:19
  def all_loaded; end

  # pkg:gem/holidays#lib/holidays/definition/repository/regions.rb:23
  def loaded?(region); end

  # pkg:gem/holidays#lib/holidays/definition/repository/regions.rb:15
  def parent_region_lookup(r); end

  # pkg:gem/holidays#lib/holidays/definition/repository/regions.rb:39
  def search(prefix); end
end

# pkg:gem/holidays#lib/holidays/definition/validator/custom_method.rb:3
module Holidays::Definition::Validator; end

# pkg:gem/holidays#lib/holidays/definition/validator/custom_method.rb:4
class Holidays::Definition::Validator::CustomMethod
  # pkg:gem/holidays#lib/holidays/definition/validator/custom_method.rb:7
  def valid?(m); end

  private

  # pkg:gem/holidays#lib/holidays/definition/validator/custom_method.rb:19
  def valid_arguments?(arguments); end

  # pkg:gem/holidays#lib/holidays/definition/validator/custom_method.rb:15
  def valid_name?(name); end

  # pkg:gem/holidays#lib/holidays/definition/validator/custom_method.rb:25
  def valid_source?(source); end
end

# pkg:gem/holidays#lib/holidays/definition/validator/custom_method.rb:5
Holidays::Definition::Validator::CustomMethod::VALID_ARGUMENTS = T.let(T.unsafe(nil), Array)

# pkg:gem/holidays#lib/holidays/definition/validator/region.rb:4
class Holidays::Definition::Validator::Region
  # pkg:gem/holidays#lib/holidays/definition/validator/region.rb:5
  def initialize(regions_repo); end

  # pkg:gem/holidays#lib/holidays/definition/validator/region.rb:9
  def valid?(r); end

  private

  # Ex: :gb_ transformed to :gb
  #
  # pkg:gem/holidays#lib/holidays/definition/validator/region.rb:22
  def find_wildcard_base(region); end
end

# pkg:gem/holidays#lib/holidays/definition/validator/test.rb:4
class Holidays::Definition::Validator::Test
  # pkg:gem/holidays#lib/holidays/definition/validator/test.rb:5
  def valid?(t); end

  private

  # pkg:gem/holidays#lib/holidays/definition/validator/test.rb:64
  def required_fields?(t); end

  # pkg:gem/holidays#lib/holidays/definition/validator/test.rb:16
  def valid_dates?(dates); end

  # Can be missing
  #
  # pkg:gem/holidays#lib/holidays/definition/validator/test.rb:44
  def valid_holiday?(h); end

  # Can be missing
  #
  # pkg:gem/holidays#lib/holidays/definition/validator/test.rb:38
  def valid_name?(n); end

  # Okay to be missing and can be either string or array of strings
  #
  # pkg:gem/holidays#lib/holidays/definition/validator/test.rb:50
  def valid_options?(options); end

  # pkg:gem/holidays#lib/holidays/definition/validator/test.rb:29
  def valid_regions?(regions); end
end

# pkg:gem/holidays#lib/holidays/errors.rb:10
class Holidays::DefinitionTestError < ::Holidays::Error; end

# pkg:gem/holidays#lib/holidays/errors.rb:2
class Holidays::Error < ::StandardError; end

# pkg:gem/holidays#lib/holidays.rb:18
Holidays::FULL_DEFINITIONS_PATH = T.let(T.unsafe(nil), String)

# pkg:gem/holidays#lib/holidays/factory/definition.rb:23
module Holidays::Factory; end

# pkg:gem/holidays#lib/holidays/factory/date_calculator.rb:9
module Holidays::Factory::DateCalculator
  class << self
    # pkg:gem/holidays#lib/holidays/factory/date_calculator.rb:41
    def day_of_month_calculator; end

    # pkg:gem/holidays#lib/holidays/factory/date_calculator.rb:33
    def hijri_date; end

    # pkg:gem/holidays#lib/holidays/factory/date_calculator.rb:29
    def lunar_date; end

    # pkg:gem/holidays#lib/holidays/factory/date_calculator.rb:37
    def weekend_modifier; end
  end
end

# pkg:gem/holidays#lib/holidays/factory/date_calculator.rb:10
module Holidays::Factory::DateCalculator::Easter; end

# pkg:gem/holidays#lib/holidays/factory/date_calculator.rb:11
module Holidays::Factory::DateCalculator::Easter::Gregorian
  class << self
    # pkg:gem/holidays#lib/holidays/factory/date_calculator.rb:13
    def easter_calculator; end
  end
end

# pkg:gem/holidays#lib/holidays/factory/date_calculator.rb:19
module Holidays::Factory::DateCalculator::Easter::Julian
  class << self
    # pkg:gem/holidays#lib/holidays/factory/date_calculator.rb:21
    def easter_calculator; end
  end
end

# pkg:gem/holidays#lib/holidays/factory/definition.rb:24
module Holidays::Factory::Definition
  class << self
    # pkg:gem/holidays#lib/holidays/factory/definition.rb:100
    def cache_repository; end

    # pkg:gem/holidays#lib/holidays/factory/definition.rb:65
    def custom_method_parser; end

    # pkg:gem/holidays#lib/holidays/factory/definition.rb:71
    def custom_method_proc_decorator; end

    # pkg:gem/holidays#lib/holidays/factory/definition.rb:75
    def custom_method_source_decorator; end

    # pkg:gem/holidays#lib/holidays/factory/definition.rb:85
    def custom_method_validator; end

    # pkg:gem/holidays#lib/holidays/factory/definition.rb:108
    def custom_methods_repository; end

    # pkg:gem/holidays#lib/holidays/factory/definition.rb:26
    def file_parser; end

    # pkg:gem/holidays#lib/holidays/factory/definition.rb:48
    def function_processor; end

    # pkg:gem/holidays#lib/holidays/factory/definition.rb:89
    def holidays_by_month_repository; end

    # pkg:gem/holidays#lib/holidays/factory/definition.rb:116
    def loader; end

    # pkg:gem/holidays#lib/holidays/factory/definition.rb:55
    def merger; end

    # pkg:gem/holidays#lib/holidays/factory/definition.rb:123
    def module_generator; end

    # pkg:gem/holidays#lib/holidays/factory/definition.rb:104
    def proc_result_cache_repository; end

    # pkg:gem/holidays#lib/holidays/factory/definition.rb:79
    def region_validator; end

    # pkg:gem/holidays#lib/holidays/factory/definition.rb:112
    def regions_generator; end

    # pkg:gem/holidays#lib/holidays/factory/definition.rb:93
    def regions_repository; end

    # pkg:gem/holidays#lib/holidays/factory/definition.rb:37
    def source_generator; end

    # pkg:gem/holidays#lib/holidays/factory/definition.rb:133
    def test_decorator; end

    # pkg:gem/holidays#lib/holidays/factory/definition.rb:127
    def test_generator; end

    # pkg:gem/holidays#lib/holidays/factory/definition.rb:137
    def test_parser; end
  end
end

# pkg:gem/holidays#lib/holidays/factory/finder.rb:12
module Holidays::Factory::Finder
  class << self
    # pkg:gem/holidays#lib/holidays/factory/finder.rb:23
    def between; end

    # pkg:gem/holidays#lib/holidays/factory/finder.rb:31
    def next_holiday; end

    # pkg:gem/holidays#lib/holidays/factory/finder.rb:47
    def parse_options; end

    # pkg:gem/holidays#lib/holidays/factory/finder.rb:14
    def search; end

    # pkg:gem/holidays#lib/holidays/factory/finder.rb:39
    def year_holiday; end

    private

    # pkg:gem/holidays#lib/holidays/factory/finder.rb:57
    def dates_driver_builder; end

    # pkg:gem/holidays#lib/holidays/factory/finder.rb:61
    def rules; end
  end
end

# pkg:gem/holidays#lib/holidays/finder/context/between.rb:2
module Holidays::Finder; end

# pkg:gem/holidays#lib/holidays/finder/context/between.rb:3
module Holidays::Finder::Context; end

# pkg:gem/holidays#lib/holidays/finder/context/between.rb:4
class Holidays::Finder::Context::Between
  # pkg:gem/holidays#lib/holidays/finder/context/between.rb:5
  def initialize(definition_search, dates_driver_builder, options_parser); end

  # pkg:gem/holidays#lib/holidays/finder/context/between.rb:11
  def call(start_date, end_date, options); end

  private

  # pkg:gem/holidays#lib/holidays/finder/context/between.rb:34
  def gather_options(observed, informal); end

  # pkg:gem/holidays#lib/holidays/finder/context/between.rb:29
  def validate!(start_date, end_date); end
end

# pkg:gem/holidays#lib/holidays/finder/context/dates_driver_builder.rb:10
class Holidays::Finder::Context::DatesDriverBuilder
  # pkg:gem/holidays#lib/holidays/finder/context/dates_driver_builder.rb:11
  def call(start_date, end_date); end

  private

  # As part of https://github.com/holidays/holidays/issues/146 I am returning
  # additional months in an attempt to catch month-spanning date situations (i.e.
  # dates falling on 2/1 but being observed on 1/31). By including the additional months
  # we are increasing runtimes slightly but improving accuracy, which is more important
  # to me at this stage.
  #
  # pkg:gem/holidays#lib/holidays/finder/context/dates_driver_builder.rb:29
  def add_border_months(current_date, dates_driver); end

  # pkg:gem/holidays#lib/holidays/finder/context/dates_driver_builder.rb:49
  def clean(dates_driver); end
end

# pkg:gem/holidays#lib/holidays/finder/context/next_holiday.rb:4
class Holidays::Finder::Context::NextHoliday
  # pkg:gem/holidays#lib/holidays/finder/context/next_holiday.rb:5
  def initialize(definition_search, dates_driver_builder, options_parser); end

  # pkg:gem/holidays#lib/holidays/finder/context/next_holiday.rb:11
  def call(holidays_count, from_date, options); end

  private

  # pkg:gem/holidays#lib/holidays/finder/context/next_holiday.rb:46
  def gather_options(observed, informal); end

  # pkg:gem/holidays#lib/holidays/finder/context/next_holiday.rb:40
  def validate!(holidays_count, from_date); end
end

# pkg:gem/holidays#lib/holidays/finder/context/parse_options.rb:4
class Holidays::Finder::Context::ParseOptions
  # pkg:gem/holidays#lib/holidays/finder/context/parse_options.rb:5
  def initialize(regions_repo, region_validator, definition_loader); end

  # Returns [(arr)regions, (bool)observed, (bool)informal]
  #
  # pkg:gem/holidays#lib/holidays/finder/context/parse_options.rb:12
  def call(*options); end

  private

  # pkg:gem/holidays#lib/holidays/finder/context/parse_options.rb:87
  def is_wildcard?(r); end

  # pkg:gem/holidays#lib/holidays/finder/context/parse_options.rb:96
  def load_region!(r); end

  # pkg:gem/holidays#lib/holidays/finder/context/parse_options.rb:91
  def load_wildcard_parent!(wildcard_region); end

  # Check regions against list of supported regions and return an array of
  # symbols.
  #
  # If a wildcard region is found (e.g. :ca_) it is expanded into all
  # of its available sub regions.
  #
  # pkg:gem/holidays#lib/holidays/finder/context/parse_options.rb:32
  def parse_regions!(regions); end

  # pkg:gem/holidays#lib/holidays/finder/context/parse_options.rb:81
  def validate!(regions); end
end

# pkg:gem/holidays#lib/holidays/finder/context/search.rb:4
class Holidays::Finder::Context::Search
  # pkg:gem/holidays#lib/holidays/finder/context/search.rb:5
  def initialize(holidays_by_month_repo, custom_method_processor, day_of_month_calculator, rules); end

  # pkg:gem/holidays#lib/holidays/finder/context/search.rb:12
  def call(dates_driver, regions, options); end

  private

  # When the queried region is :any (or no holiday_regions are provided), fall back
  # to the holiday's own first region. Otherwise use the first queried region that
  # also appears in the holiday's region list so that region-specific function
  # implementations resolve correctly even when a holiday definition is shared across
  # multiple regions.
  #
  # pkg:gem/holidays#lib/holidays/finder/context/search.rb:108
  def build_custom_method_input(year, month, day, queried_regions, holiday_regions = T.unsafe(nil)); end

  # pkg:gem/holidays#lib/holidays/finder/context/search.rb:76
  def build_date(year, month, h, queried_regions); end

  # Observed methods default to taking only a date, but they may declare
  # additional arguments such as :region so that a single definition shared
  # across regions can observe differently in one of them.
  #
  # pkg:gem/holidays#lib/holidays/finder/context/search.rb:126
  def build_observed_date(date, regions, h); end

  # pkg:gem/holidays#lib/holidays/finder/context/search.rb:85
  def custom_holidays(year, month, h, queried_regions); end

  # pkg:gem/holidays#lib/holidays/finder/context/search.rb:68
  def informal_set?(options); end

  # pkg:gem/holidays#lib/holidays/finder/context/search.rb:64
  def informal_type?(type); end

  # pkg:gem/holidays#lib/holidays/finder/context/search.rb:72
  def observed_set?(options); end

  # pkg:gem/holidays#lib/holidays/finder/context/search.rb:52
  def validate!(dates_driver); end
end

# pkg:gem/holidays#lib/holidays/finder/context/year_holiday.rb:4
class Holidays::Finder::Context::YearHoliday
  # pkg:gem/holidays#lib/holidays/finder/context/year_holiday.rb:5
  def initialize(definition_search, dates_driver_builder, options_parser); end

  # pkg:gem/holidays#lib/holidays/finder/context/year_holiday.rb:11
  def call(from_date, options); end

  private

  # pkg:gem/holidays#lib/holidays/finder/context/year_holiday.rb:46
  def gather_options(observed, informal); end

  # pkg:gem/holidays#lib/holidays/finder/context/year_holiday.rb:42
  def validate!(from_date); end
end

# pkg:gem/holidays#lib/holidays/finder/rules/in_region.rb:3
module Holidays::Finder::Rules; end

# pkg:gem/holidays#lib/holidays/finder/rules/in_region.rb:4
class Holidays::Finder::Rules::InRegion
  class << self
    # pkg:gem/holidays#lib/holidays/finder/rules/in_region.rb:6
    def call(requested, available); end
  end
end

# pkg:gem/holidays#lib/holidays/finder/rules/year_range.rb:4
class Holidays::Finder::Rules::YearRange
  class << self
    # pkg:gem/holidays#lib/holidays/finder/rules/year_range.rb:11
    def call(target_year, year_range_defs); end

    private

    # pkg:gem/holidays#lib/holidays/finder/rules/year_range.rb:35
    def validate!(target_year, year_ranges); end
  end
end

# pkg:gem/holidays#lib/holidays/errors.rb:4
class Holidays::FunctionNotFound < ::Holidays::Error; end

# pkg:gem/holidays#lib/holidays/errors.rb:5
class Holidays::InvalidFunctionResponse < ::Holidays::Error; end

# pkg:gem/holidays#lib/holidays/errors.rb:8
class Holidays::InvalidRegion < ::Holidays::Error; end

# pkg:gem/holidays#lib/holidays.rb:14
Holidays::MONTH_LENGTHS = T.let(T.unsafe(nil), Array)

# pkg:gem/holidays#lib/generated_definitions/REGIONS.rb:5
Holidays::PARENT_REGION_LOOKUP = T.let(T.unsafe(nil), Hash)

# pkg:gem/holidays#lib/generated_definitions/REGIONS.rb:3
Holidays::REGIONS = T.let(T.unsafe(nil), Array)

# pkg:gem/holidays#lib/generated_definitions/REGIONS.rb:7
Holidays::REGION_NAMES = T.let(T.unsafe(nil), Hash)

# pkg:gem/holidays#lib/holidays/errors.rb:7
class Holidays::UnknownRegionError < ::Holidays::Error; end

# pkg:gem/holidays#lib/holidays.rb:13
Holidays::WEEKS = T.let(T.unsafe(nil), Hash)
