# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `resque-scheduler` gem.
# Please instead update this file by running `bin/tapioca gem resque-scheduler`.


# vim:fileencoding=utf-8
# $PROCESS_ID
# vim:fileencoding=utf-8
# vim:fileencoding=utf-8
# vim:fileencoding=utf-8
# Extend Resque::Server to add tabs
# vim:fileencoding=utf-8
# vim:fileencoding=utf-8
# vim:fileencoding=utf-8
#
# pkg:gem/resque-scheduler#lib/resque/scheduler/configuration.rb:3
module Resque
  extend ::Resque::Helpers
  extend ::Resque::Scheduler::SchedulingExtensions
  extend ::Resque::Scheduler::DelayingExtensions
  extend ::Resque::Scheduler::Extension
end

# pkg:gem/resque-scheduler#lib/resque/scheduler/configuration.rb:4
module Resque::Scheduler
  extend ::Resque::Scheduler::Locking
  extend ::Resque::Scheduler::Configuration
  extend ::Resque::Scheduler::SignalHandling

  class << self
    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:445
    def before_shutdown; end

    # Stops old rufus scheduler and creates a new one.  Returns the new
    # rufus scheduler
    #
    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:359
    def clear_schedule!; end

    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:285
    def enqueue(config); end

    # Enqueues all delayed jobs for a timestamp
    #
    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:208
    def enqueue_delayed_items_for_timestamp(timestamp); end

    # Enqueues a job based on a config hash
    #
    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:298
    def enqueue_from_config(job_config); end

    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:241
    def enqueue_items_in_batch_for_timestamp(timestamp, batch_size); end

    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:196
    def enqueue_next_item(timestamp); end

    # Returns true if the current env is non-nil and the configured env
    # (which is a comma-split string) includes the current env.
    #
    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:179
    def env_matches?(configured_env); end

    # allow user to set an additional failure handler
    #
    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:477
    def failure_handler; end

    # allow user to set an additional failure handler
    #
    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:36
    def failure_handler=(_arg0); end

    # Handles queueing delayed items
    # at_time - Time to start scheduling items (default: now).
    #
    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:185
    def handle_delayed_items(at_time = T.unsafe(nil)); end

    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:291
    def handle_shutdown; end

    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:432
    def handle_signals_with_operation; end

    # Pulls the schedule from Resque.schedule and loads it into the
    # rufus scheduler instance
    #
    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:97
    def load_schedule!; end

    # Loads a job schedule into the Rufus::Scheduler and stores it
    # in @scheduled_jobs
    #
    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:134
    def load_schedule_job(name, config); end

    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:466
    def log(msg); end

    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:458
    def log!(msg); end

    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:462
    def log_error(msg); end

    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:481
    def logger; end

    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:30
    def logger=(_arg0); end

    # modify interval type value to value with options if options available
    #
    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:115
    def optionizate_interval_value(value); end

    # Sleeps and returns true
    #
    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:399
    def poll_sleep; end

    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:410
    def poll_sleep_loop; end

    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:85
    def print_schedule; end

    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:470
    def procline(string); end

    # Returns true if the given schedule config hash matches the current env
    #
    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:170
    def rails_env_matches?(config); end

    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:366
    def reload_schedule!; end

    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:353
    def rufus_scheduler; end

    # Schedule all jobs and continually look for delayed jobs (never returns)
    #
    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:39
    def run; end

    # the Rufus::Scheduler jobs that are scheduled
    #
    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:33
    def scheduled_jobs; end

    # Sets the shutdown flag, clean schedules and exits if sleeping
    #
    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:451
    def shutdown; end

    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:441
    def stop_rufus_scheduler; end

    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:237
    def timestamp_key(timestamp); end

    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:390
    def unschedule_job(name); end

    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:372
    def update_schedule; end

    private

    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:516
    def am_master; end

    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:500
    def app_str; end

    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:508
    def build_procline(string); end

    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:492
    def enqueue_recurring(name, config); end

    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:504
    def env_str; end

    # pkg:gem/resque-scheduler#lib/resque/scheduler.rb:512
    def internal_name; end
  end
end

# pkg:gem/resque-scheduler#lib/resque/scheduler/cli.rb:7
Resque::Scheduler::CLI_OPTIONS_ENV_MAPPING = T.let(T.unsafe(nil), Hash)

# pkg:gem/resque-scheduler#lib/resque/scheduler/cli.rb:22
class Resque::Scheduler::Cli
  # pkg:gem/resque-scheduler#lib/resque/scheduler/cli.rb:84
  def initialize(argv = T.unsafe(nil), env = T.unsafe(nil)); end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/cli.rb:100
  def parse_options; end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/cli.rb:94
  def pre_run; end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/cli.rb:104
  def pre_setup; end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/cli.rb:89
  def run!; end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/cli.rb:117
  def run_forever; end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/cli.rb:112
  def setup_env; end

  private

  # pkg:gem/resque-scheduler#lib/resque/scheduler/cli.rb:123
  def argv; end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/cli.rb:123
  def env; end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/cli.rb:129
  def option_parser; end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/cli.rb:139
  def options; end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/cli.rb:125
  def runtime_env; end

  class << self
    # pkg:gem/resque-scheduler#lib/resque/scheduler/cli.rb:80
    def run!(argv = T.unsafe(nil), env = T.unsafe(nil)); end
  end
end

# pkg:gem/resque-scheduler#lib/resque/scheduler/cli.rb:23
Resque::Scheduler::Cli::BANNER = T.let(T.unsafe(nil), String)

# pkg:gem/resque-scheduler#lib/resque/scheduler/cli.rb:29
Resque::Scheduler::Cli::OPTIONS = T.let(T.unsafe(nil), Array)

# pkg:gem/resque-scheduler#lib/resque/scheduler/configuration.rb:5
module Resque::Scheduler::Configuration
  # If set, will append the app name to procline
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/configuration.rb:64
  def app_name; end

  # If set, will append the app name to procline
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/configuration.rb:62
  def app_name=(_arg0); end

  # Allows for block-style configuration
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/configuration.rb:7
  def configure; end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/configuration.rb:68
  def delayed_requeue_batch_size; end

  # If set, will try to update the schedule in the loop
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/configuration.rb:57
  def dynamic; end

  # If set, will try to update the schedule in the loop
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/configuration.rb:55
  def dynamic=(_arg0); end

  # Used in `#load_schedule_job`
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/configuration.rb:19
  def env; end

  # Used in `#load_schedule_job`
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/configuration.rb:17
  def env=(_arg0); end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/configuration.rb:12
  def environment; end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/configuration.rb:11
  def environment=(_arg0); end

  # Sets timeout for Resque::Scheduler::Lock::Base
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/configuration.rb:86
  def lock_timeout; end

  # Sets timeout for Resque::Scheduler::Lock::Base
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/configuration.rb:84
  def lock_timeout=(_arg0); end

  # If set, will write messages to the file
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/configuration.rb:43
  def logfile; end

  # If set, will write messages to the file
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/configuration.rb:41
  def logfile=(_arg0); end

  # Sets whether to log in 'text', 'json' or 'logfmt'
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/configuration.rb:50
  def logformat; end

  # Sets whether to log in 'text', 'json' or 'logfmt'
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/configuration.rb:48
  def logformat=(_arg0); end

  # Amount of time in seconds to sleep between polls of the delayed
  # queue.  Defaults to 5
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/configuration.rb:78
  def poll_sleep_amount; end

  # Amount of time in seconds to sleep between polls of the delayed
  # queue.  Defaults to 5
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/configuration.rb:76
  def poll_sleep_amount=(_arg0); end

  # If set, produces no output
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/configuration.rb:36
  def quiet; end

  # If set, produces no output
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/configuration.rb:34
  def quiet=(_arg0); end

  # If true, logs more stuff...
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/configuration.rb:29
  def verbose; end

  # If true, logs more stuff...
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/configuration.rb:27
  def verbose=(_arg0); end

  private

  # pkg:gem/resque-scheduler#lib/resque/scheduler/configuration.rb:104
  def to_bool(value); end
end

# Copied from https://github.com/rails/rails/blob/main/activemodel/lib/active_model/type/boolean.rb#L17
#
# pkg:gem/resque-scheduler#lib/resque/scheduler/configuration.rb:93
Resque::Scheduler::Configuration::TRUE_VALUES = T.let(T.unsafe(nil), Set)

# pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:7
module Resque::Scheduler::DelayingExtensions
  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:297
  def clean_up_timestamp(key, timestamp); end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:264
  def count_all_scheduled_jobs; end

  # Update the delayed timestamp of any matching delayed jobs or enqueue a
  # new job if no matching jobs are found. Returns the number of delayed or
  # enqueued jobs.
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:66
  def delay_or_enqueue_at(timestamp, klass, *args); end

  # Identical to +delay_or_enqueue_at+, except it takes
  # number_of_seconds_from_now instead of a timestamp
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:77
  def delay_or_enqueue_in(number_of_seconds_from_now, klass, *args); end

  # Discover if a job has been delayed.
  # Examples
  #   Resque.delayed?(MyJob)
  #   Resque.delayed?(MyJob, id: 1)
  # Returns true if the job has been delayed
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:277
  def delayed?(klass, *args); end

  # Used internally to stuff the item into the schedule sorted list.
  # +timestamp+ can be either in seconds or a datetime object. The
  # insertion time complexity is O(log(n)). Returns true if it's
  # the first job to be scheduled at that time, else false.
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:85
  def delayed_push(timestamp, item); end

  # Returns an array of timestamps based on start and count
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:99
  def delayed_queue_peek(start, count); end

  # Returns the size of the delayed queue schedule
  # this does not represent the number of items in the queue to be scheduled
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:107
  def delayed_queue_schedule_size; end

  # Returns an array of delayed items for the given timestamp
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:118
  def delayed_timestamp_peek(timestamp, start, count); end

  # Returns the number of jobs for a given timestamp in the delayed queue
  # schedule
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:113
  def delayed_timestamp_size(timestamp); end

  # This method is nearly identical to +enqueue+ only it also
  # takes a timestamp which will be used to schedule the job
  # for queueing.  Until timestamp is in the past, the job will
  # sit in the schedule list.
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:12
  def enqueue_at(timestamp, klass, *args); end

  # Identical to +enqueue_at+, except you can also specify
  # a queue in which the job will be placed after the
  # timestamp has passed. It respects Resque.inline option, by
  # creating the job right away instead of adding to the queue.
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:23
  def enqueue_at_with_queue(queue, timestamp, klass, *args); end

  # Given an encoded item, enqueue it now
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:171
  def enqueue_delayed(klass, *args); end

  # Given a block, enqueue jobs now that return true from a block
  #
  # This allows for enqueuing of delayed jobs that have arguments matching
  # certain criteria
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:202
  def enqueue_delayed_selection(klass = T.unsafe(nil)); end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:178
  def enqueue_delayed_with_queue(klass, queue, *args); end

  # Identical to enqueue_at but takes number_of_seconds_from_now
  # instead of a timestamp.
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:44
  def enqueue_in(number_of_seconds_from_now, klass, *args); end

  # Identical to +enqueue_in+, except you can also specify
  # a queue in which the job will be placed after the
  # number of seconds has passed.
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:54
  def enqueue_in_with_queue(queue, number_of_seconds_from_now, klass, *args); end

  # Given a block, find jobs that return true from a block
  #
  # This allows for finding of delayed jobs that have arguments matching
  # certain criteria
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:225
  def find_delayed_selection(klass = T.unsafe(nil), &block); end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:293
  def get_last_enqueued_at(job_name); end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:289
  def last_enqueued_at(job_name, date); end

  # Returns the next delayed queue timestamp
  # (don't call directly)
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:129
  def next_delayed_timestamp(at_time = T.unsafe(nil)); end

  # Returns the next item to be processed for a given timestamp, nil if
  # done. (don't call directly)
  # +timestamp+ can either be in seconds or a datetime
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:136
  def next_item_for_timestamp(timestamp); end

  # Given an encoded item, remove it from the delayed_queue
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:160
  def remove_delayed(klass, *args); end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:165
  def remove_delayed_in_queue(klass, queue, *args); end

  # Given a timestamp and job (klass + args) it removes all instances and
  # returns the count of jobs removed.
  #
  # O(N) where N is the number of jobs scheduled to fire at the given
  # timestamp
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:251
  def remove_delayed_job_from_timestamp(timestamp, klass, *args); end

  # Given a block, remove jobs that return true from a block
  #
  # This allows for removal of delayed jobs that have arguments matching
  # certain criteria
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:189
  def remove_delayed_selection(klass = T.unsafe(nil)); end

  # Clears all jobs created with enqueue_at or enqueue_in
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:149
  def reset_delayed_queue; end

  # Returns delayed jobs schedule timestamp for +klass+, +args+.
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:282
  def scheduled_at(klass, *args); end

  private

  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:315
  def job_to_hash(klass, args); end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:319
  def job_to_hash_with_queue(queue, klass, args); end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:356
  def payload_matches_selection?(decoded_payload, klass); end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:363
  def plugin; end

  # Removes a job from the queue, but not modify the timestamp schedule. This method
  # will not effect the output of `delayed_queue_schedule_size`
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:325
  def remove_delayed_job(encoded_job); end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/delaying_extensions.rb:344
  def search_first_delayed_timestamp_in_range(start_at, stop_at); end
end

# pkg:gem/resque-scheduler#lib/resque/scheduler/extension.rb:8
module Resque::Scheduler::Extension
  include ::Resque::Scheduler::SchedulingExtensions
  include ::Resque::Scheduler::DelayingExtensions
end

# pkg:gem/resque-scheduler#lib/resque/scheduler/failure_handler.rb:3
class Resque::Scheduler::FailureHandler
  class << self
    # pkg:gem/resque-scheduler#lib/resque/scheduler/failure_handler.rb:4
    def on_enqueue_failure(_, e); end
  end
end

# pkg:gem/resque-scheduler#lib/resque/scheduler.rb:17
Resque::Scheduler::INTERMITTENT_ERRORS = T.let(T.unsafe(nil), Array)

# pkg:gem/resque-scheduler#lib/resque/scheduler/lock/base.rb:5
module Resque::Scheduler::Lock; end

# pkg:gem/resque-scheduler#lib/resque/scheduler/lock/base.rb:6
class Resque::Scheduler::Lock::Base
  # pkg:gem/resque-scheduler#lib/resque/scheduler/lock/base.rb:10
  def initialize(key, options = T.unsafe(nil)); end

  # Attempts to acquire the lock. Returns true if successfully acquired.
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/lock/base.rb:18
  def acquire!; end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/lock/base.rb:7
  def key; end

  # Returns true if you currently hold the lock.
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/lock/base.rb:27
  def locked?; end

  # Releases the lock iff we own it
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/lock/base.rb:37
  def release; end

  # Releases the lock.
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/lock/base.rb:32
  def release!; end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/lock/base.rb:8
  def timeout; end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/lock/base.rb:8
  def timeout=(_arg0); end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/lock/base.rb:22
  def value; end

  private

  # Extends the lock by `timeout` seconds.
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/lock/base.rb:44
  def extend_lock!; end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/lock/base.rb:48
  def hostname; end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/lock/base.rb:55
  def process_id; end
end

# pkg:gem/resque-scheduler#lib/resque/scheduler/lock/basic.rb:7
class Resque::Scheduler::Lock::Basic < ::Resque::Scheduler::Lock::Base
  # pkg:gem/resque-scheduler#lib/resque/scheduler/lock/basic.rb:8
  def acquire!; end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/lock/basic.rb:15
  def locked?; end
end

# pkg:gem/resque-scheduler#lib/resque/scheduler/lock/resilient.rb:7
class Resque::Scheduler::Lock::Resilient < ::Resque::Scheduler::Lock::Base
  # pkg:gem/resque-scheduler#lib/resque/scheduler/lock/resilient.rb:8
  def acquire!; end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/lock/resilient.rb:12
  def locked?; end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/lock/resilient.rb:16
  def timeout=(seconds); end

  private

  # pkg:gem/resque-scheduler#lib/resque/scheduler/lock/resilient.rb:61
  def acquire_sha(refresh = T.unsafe(nil)); end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/lock/resilient.rb:27
  def evalsha(script, keys, argv, refresh: T.unsafe(nil)); end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/lock/resilient.rb:42
  def locked_sha(refresh = T.unsafe(nil)); end
end

# pkg:gem/resque-scheduler#lib/resque/scheduler/locking.rb:56
module Resque::Scheduler::Locking
  # pkg:gem/resque-scheduler#lib/resque/scheduler/locking.rb:65
  def master?; end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/locking.rb:57
  def master_lock; end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/locking.rb:77
  def release_master_lock; end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/locking.rb:69
  def release_master_lock!; end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/locking.rb:61
  def supports_lua?; end

  private

  # pkg:gem/resque-scheduler#lib/resque/scheduler/locking.rb:85
  def build_master_lock; end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/locking.rb:93
  def master_lock_key; end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/locking.rb:99
  def redis_master_version; end
end

# Just builds a logger, with specified verbosity and destination.
# The simplest example:
#
#   Resque::Scheduler::LoggerBuilder.new.build
#
# pkg:gem/resque-scheduler#lib/resque/scheduler/logger_builder.rb:11
class Resque::Scheduler::LoggerBuilder
  # Initializes new instance of the builder
  #
  # Pass :opts Hash with
  #   - :quiet if logger needs to be silent for all levels. Default - false
  #   - :verbose if there is a need in debug messages. Default - false
  #   - :log_dev to output logs into a desired file. Default - STDOUT
  #   - :format log format, either 'text', 'json' or 'logfmt'. Default - 'text'
  #
  # Example:
  #
  #   LoggerBuilder.new(
  #     :quiet => false, :verbose => true, :log_dev => 'log/scheduler.log'
  #   )
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/logger_builder.rb:25
  def initialize(opts = T.unsafe(nil)); end

  # Returns an instance of MonoLogger
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/logger_builder.rb:33
  def build; end

  private

  # pkg:gem/resque-scheduler#lib/resque/scheduler/logger_builder.rb:59
  def json_formatter; end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/logger_builder.rb:43
  def level; end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/logger_builder.rb:73
  def logfmt_formatter; end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/logger_builder.rb:53
  def text_formatter; end
end

# pkg:gem/resque-scheduler#lib/resque/scheduler/plugin.rb:5
module Resque::Scheduler::Plugin
  class << self
    # pkg:gem/resque-scheduler#lib/resque/scheduler/plugin.rb:15
    def hooks(job, pattern); end

    # pkg:gem/resque-scheduler#lib/resque/scheduler/plugin.rb:6
    def process_schedule_hooks(klass, *args); end

    # pkg:gem/resque-scheduler#lib/resque/scheduler/plugin.rb:35
    def run_after_schedule_hooks(klass, *args); end

    # pkg:gem/resque-scheduler#lib/resque/scheduler/plugin.rb:27
    def run_before_delayed_enqueue_hooks(klass, *args); end

    # pkg:gem/resque-scheduler#lib/resque/scheduler/plugin.rb:31
    def run_before_schedule_hooks(klass, *args); end

    # pkg:gem/resque-scheduler#lib/resque/scheduler/plugin.rb:19
    def run_hooks(job, pattern, *args); end
  end
end

# pkg:gem/resque-scheduler#lib/resque/scheduler/scheduling_extensions.rb:5
module Resque::Scheduler::SchedulingExtensions
  # gets the schedules as it exists in redis
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/scheduling_extensions.rb:70
  def all_schedules; end

  # retrive the schedule configuration for the given name
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/scheduling_extensions.rb:99
  def fetch_schedule(name); end

  # reloads the schedule from redis and memory
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/scheduling_extensions.rb:65
  def reload_schedule!; end

  # remove a given schedule by name
  # Preventing a reload is optional and available to batch operations
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/scheduling_extensions.rb:105
  def remove_schedule(name, reload = T.unsafe(nil)); end

  # Returns the schedule hash
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/scheduling_extensions.rb:59
  def schedule; end

  # Accepts a new schedule configuration of the form:
  #
  #   {
  #     "MakeTea" => {
  #       "every" => "1m" },
  #     "some_name" => {
  #       "cron"        => "5/* * * *",
  #       "class"       => "DoSomeWork",
  #       "args"        => "work on this string",
  #       "description" => "this thing works it"s butter off" },
  #     ...
  #   }
  #
  # Hash keys can be anything and are used to describe and reference
  # the scheduled job. If the "class" argument is missing, the key
  # is used implicitly as "class" argument - in the "MakeTea" example,
  # "MakeTea" is used both as job name and resque worker class.
  #
  # Any jobs that were in the old schedule, but are not
  # present in the new schedule, will be removed.
  #
  # :cron can be any cron scheduling string
  #
  # :every can be used in lieu of :cron. see rufus-scheduler's 'every'
  # usage for valid syntax. If :cron is present it will take precedence
  # over :every.
  #
  # :class must be a resque worker class. If it is missing, the job name
  # (hash key) will be used as :class.
  #
  # :args can be any yaml which will be converted to a ruby literal and
  # passed in a params. (optional)
  #
  # :rails_env is the list of envs where the job gets loaded. Envs are
  # comma separated (optional)
  #
  # :description is just that, a description of the job (optional). If
  # params is an array, each element in the array is passed as a separate
  # param, otherwise params is passed in as the only parameter to
  # perform.
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/scheduling_extensions.rb:46
  def schedule=(schedule_hash); end

  # Create or update a schedule with the provided name and configuration.
  #
  # Note: values for class and custom_job_class need to be strings,
  # not constants.
  #
  #    Resque.set_schedule('some_job', {:class => 'SomeJob',
  #                                     :every => '15mins',
  #                                     :queue => 'high',
  #                                     :args => '/tmp/poop'})
  #
  # Preventing a reload is optional and available to batch operations
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/scheduling_extensions.rb:85
  def set_schedule(name, config, reload = T.unsafe(nil)); end

  private

  # we store our non-persistent schedules in this hash
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/scheduling_extensions.rb:116
  def non_persistent_schedules; end

  # reads the persistent schedules from redis
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/scheduling_extensions.rb:121
  def persistent_schedules; end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/scheduling_extensions.rb:129
  def prepare_schedules(schedule_hash); end
end

# pkg:gem/resque-scheduler#lib/resque/scheduler/signal_handling.rb:5
module Resque::Scheduler::SignalHandling
  # pkg:gem/resque-scheduler#lib/resque/scheduler/signal_handling.rb:26
  def handle_signals; end

  # For all signals, set the shutdown flag and wait for current
  # poll/enqueuing to finish (should be almost instant).  In the
  # case of sleeping, exit immediately.
  #
  # pkg:gem/resque-scheduler#lib/resque/scheduler/signal_handling.rb:15
  def register_signal_handlers; end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/signal_handling.rb:8
  def signal_queue; end

  # pkg:gem/resque-scheduler#lib/resque/scheduler/signal_handling.rb:6
  def signal_queue=(_arg0); end
end

# pkg:gem/resque-scheduler#lib/resque/scheduler/util.rb:5
class Resque::Scheduler::Util
  class << self
    # pkg:gem/resque-scheduler#lib/resque/scheduler/util.rb:34
    def classify(dashed_word); end

    # In order to upgrade to resque(1.25) which has deprecated following
    # methods, we just added these useful helpers back to use in Resque
    # Scheduler.  refer to:
    # https://github.com/resque/resque-scheduler/pull/273
    #
    # pkg:gem/resque-scheduler#lib/resque/scheduler/util.rb:11
    def constantize(camel_cased_word); end
  end
end

# pkg:gem/resque-scheduler#lib/resque/scheduler/version.rb:5
Resque::Scheduler::VERSION = T.let(T.unsafe(nil), String)
